export const demandTypes = [
  {
    key: "incidente",
    label: "Incidente",
    description: "Falha, ocorrencia ou degradacao operacional.",
    defaultPriority: "high",
    canGenerateServiceOrder: true,
    canAppearInShiftLog: true,
    defaultQueue: "operacional-n1",
  },
  {
    key: "solicitacao",
    label: "Solicitacao",
    description: "Pedido de atendimento, apoio ou servico tecnico.",
    defaultPriority: "medium",
    canGenerateServiceOrder: true,
    canAppearInShiftLog: true,
    defaultQueue: "triagem-tecnica",
  },
  {
    key: "vistoria",
    label: "Vistoria",
    description: "Verificacao tecnica planejada ou sob demanda.",
    defaultPriority: "medium",
    canGenerateServiceOrder: true,
    canAppearInShiftLog: false,
    defaultQueue: "supervisao-tecnica",
  },
  {
    key: "manutencao",
    label: "Manutencao",
    description: "Demanda ligada a manutencao corretiva, preventiva ou tecnica.",
    defaultPriority: "medium",
    canGenerateServiceOrder: true,
    canAppearInShiftLog: true,
    defaultQueue: "supervisao-tecnica",
  },
  {
    key: "pendencia_turno",
    label: "Pendencia de Turno",
    description: "Pendencia registrada em turno para continuidade operacional.",
    defaultPriority: "medium",
    canGenerateServiceOrder: true,
    canAppearInShiftLog: true,
    defaultQueue: "livro-turno",
  },
  {
    key: "atividade_planejada",
    label: "Atividade Planejada",
    description: "Atividade tecnica ou administrativa previamente planejada.",
    defaultPriority: "medium",
    canGenerateServiceOrder: true,
    canAppearInShiftLog: false,
    defaultQueue: "planejamento-tecnico",
  },
  {
    key: "administrativo",
    label: "Administrativo",
    description: "Atividade administrativa interna da secao tecnica.",
    defaultPriority: "low",
    canGenerateServiceOrder: true,
    canAppearInShiftLog: false,
    defaultQueue: "secretaria-tecnica",
  },
] as const;

export type DemandTypeKey = (typeof demandTypes)[number]["key"];
