export const businessRoles = [
  {
    key: "technician_trainee",
    legacyLevel: "trainee",
    label: "Tecnico Trainee",
    canExecuteServiceOrder: true,
    requiresSupervision: true,
    canApprove: false,
    canAssignServiceOrder: false,
  },
  {
    key: "technician_pleno",
    legacyLevel: "pleno",
    label: "Tecnico Pleno",
    canExecuteServiceOrder: true,
    requiresSupervision: false,
    canApprove: false,
    canAssignServiceOrder: false,
  },
  {
    key: "technician_specialist",
    legacyLevel: "especialista",
    label: "Tecnico Especialista",
    canExecuteServiceOrder: true,
    requiresSupervision: false,
    canApprove: false,
    canAssignServiceOrder: false,
    canValidateTechnicalWork: true,
  },
  {
    key: "technical_supervisor",
    legacyLevel: "supervisor",
    label: "Supervisor Tecnico",
    canExecuteServiceOrder: true,
    canAssignServiceOrder: true,
    canApprove: true,
    canReviewShiftLog: true,
    canValidateTechnicalWork: true,
  },
  {
    key: "technical_secretary",
    label: "Secretario Tecnico-Operacional",
    canPrepareDocuments: true,
    canReviewCompleteness: true,
    canApprove: false,
    canExecuteServiceOrder: false,
  },
  {
    key: "acting_chief",
    label: "Chefe Interino",
    canApprove: true,
    canPlanMaintenance: true,
    canManageAcquisitions: true,
    canAssignServiceOrder: true,
  },
] as const;

export type BusinessRoleKey = (typeof businessRoles)[number]["key"];
