export type RuntimeErrorCode =
  | "INVALID_INPUT"
  | "WORKSPACE_REQUIRED"
  | "WORKSPACE_MISMATCH"
  | "PROCESS_VERSION_NOT_FOUND"
  | "PROCESS_VERSION_NOT_PUBLISHED"
  | "PROCESS_VERSION_WORKSPACE_MISMATCH"
  | "INVALID_PROCESS_DEFINITION"
  | "INITIAL_NODE_NOT_FOUND"
  | "INSTANCE_NOT_FOUND"
  | "INSTANCE_NOT_ACTIVE"
  | "ACTION_EXECUTION_NOT_FOUND"
  | "ACTION_EXECUTION_NOT_ACTIVE"
  | "INVALID_STATE_TRANSITION"
  | "AMBIGUOUS_TRANSITION"
  | "NO_VALID_TRANSITION"
  | "CONCURRENT_MODIFICATION"
  | "DUPLICATE_COMMAND"
  | "PAYLOAD_VALIDATION_FAILED"
  | "EVENT_WRITE_FAILED"
  | "OUTBOX_WRITE_FAILED"
  | "INTERNAL_ERROR";

export interface RuntimeError {
  code: RuntimeErrorCode;
  message: string;
}

export type RuntimeResult<T> =
  | { ok: true; data: T }
  | { ok: false; error: RuntimeError };
