import { CapabilityItem } from './capability-types';

export const MOCK_CAPABILITIES: CapabilityItem[] = [
  // MVP Core
  {
    id: 'cap-org-001',
    slug: 'organization',
    name: 'Organization',
    category: 'foundation',
    description: 'Manages organizational structure, divisions, workspaces, and generic metadata.',
    core_business: false,
    mvp_priority: 'critical',
    status: 'documented',
    depends_on: [],
    used_by: ['people', 'requests', 'work_orders', 'assets'],
    owns_entities: ['Workspace', 'Division', 'OrgUnit'],
    does_not_own: ['User'],
    main_processes: ['Register Workspace', 'Manage Structure'],
    main_events: ['workspace.created', 'division.updated'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-peo-001',
    slug: 'people',
    name: 'People',
    category: 'foundation',
    description: 'Manages users, teams, skills, and roles within the platform.',
    core_business: false,
    mvp_priority: 'critical',
    status: 'documented',
    depends_on: ['organization'],
    used_by: ['requests', 'work_orders', 'approvals'],
    owns_entities: ['User', 'Team', 'Skill'],
    does_not_own: ['Workspace'],
    main_processes: ['User Onboarding', 'Team Assignment'],
    main_events: ['user.registered', 'team.updated'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-req-001',
    slug: 'requests',
    name: 'Requests',
    category: 'work-management',
    description: 'Handles generic intake of demands, incidents, or service requests.',
    core_business: true,
    mvp_priority: 'critical',
    status: 'documented',
    depends_on: ['organization', 'people'],
    used_by: ['work_orders', 'cases'],
    owns_entities: ['Request', 'IntakeForm'],
    does_not_own: ['WorkOrder', 'User'],
    main_processes: ['Submit Request', 'Triage Request'],
    main_events: ['request.submitted', 'request.triaged'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [
      { type: 'overlap', description: 'May overlap with specific Cases or external ticketers.' }
    ],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-wo-001',
    slug: 'work_orders',
    name: 'Work Orders',
    category: 'work-management',
    description: 'Execution-focused capability managing tasks, materials, and field actions.',
    core_business: true,
    mvp_priority: 'critical',
    status: 'documented',
    depends_on: ['organization', 'people', 'requests'],
    used_by: ['scheduling', 'inventory'],
    owns_entities: ['WorkOrder', 'Task', 'MaterialUsage'],
    does_not_own: ['Request', 'Asset', 'InventoryItem'],
    main_processes: ['Plan Work', 'Execute Work', 'Complete Work'],
    main_events: ['work_order.planned', 'work_order.completed'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-doc-001',
    slug: 'documents',
    name: 'Documents',
    category: 'information',
    description: 'Centralized storage and management of files, attachments, and static records.',
    core_business: false,
    mvp_priority: 'critical',
    status: 'documented',
    depends_on: ['organization'],
    used_by: ['work_orders', 'contracts', 'legal'],
    owns_entities: ['Document', 'Folder', 'Attachment'],
    does_not_own: ['WorkOrder'],
    main_processes: ['Upload Document', 'Version Document'],
    main_events: ['document.uploaded'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-aud-001',
    slug: 'audit',
    name: 'Audit',
    category: 'control',
    description: 'Immutable historical logging of system events and entity changes.',
    core_business: false,
    mvp_priority: 'critical',
    status: 'documented',
    depends_on: [],
    used_by: ['compliance'],
    owns_entities: ['AuditTrail', 'SystemLog'],
    does_not_own: [],
    main_processes: ['Log Event', 'Query History'],
    main_events: [],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-com-001',
    slug: 'communication',
    name: 'Communication',
    category: 'relationship',
    description: 'Handles internal messages, notifications, emails, and external comms.',
    core_business: false,
    mvp_priority: 'critical',
    status: 'documented',
    depends_on: ['people'],
    used_by: ['requests', 'work_orders', 'approvals'],
    owns_entities: ['Notification', 'Message', 'Channel'],
    does_not_own: ['User'],
    main_processes: ['Send Notification', 'Receive Message'],
    main_events: ['notification.sent'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-sch-001',
    slug: 'scheduling',
    name: 'Scheduling',
    category: 'resource',
    description: 'Manages calendars, shifts, availability, and time-based assignments.',
    core_business: false,
    mvp_priority: 'critical',
    status: 'documented',
    depends_on: ['people'],
    used_by: ['work_orders'],
    owns_entities: ['Calendar', 'Event', 'Shift'],
    does_not_own: ['User', 'WorkOrder'],
    main_processes: ['Schedule Event', 'Manage Availability'],
    main_events: ['event.scheduled'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-tsk-001',
    slug: 'tasks',
    name: 'Tasks',
    category: 'work-management',
    description: 'Granular units of work inside larger orders or requests.',
    core_business: true,
    mvp_priority: 'critical',
    status: 'documented',
    depends_on: ['organization', 'people'],
    used_by: ['work_orders', 'cases'],
    owns_entities: ['Task', 'Checklist'],
    does_not_own: ['WorkOrder', 'Case'],
    main_processes: ['Execute Task', 'Verify Checklist'],
    main_events: ['task.completed'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [
      { type: 'composition', description: 'Tasks usually belong to parent Work Orders or Cases.' }
    ],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },

  // Complementary
  {
    id: 'cap-ast-001',
    slug: 'assets',
    name: 'Assets',
    category: 'resource',
    description: 'Manages physical and logical assets, equipment, and locations.',
    core_business: true,
    mvp_priority: 'high',
    status: 'needs_review',
    depends_on: ['organization'],
    used_by: ['work_orders', 'inventory'],
    owns_entities: ['Asset', 'Location', 'AssetType'],
    does_not_own: ['WorkOrder'],
    main_processes: ['Register Asset', 'Decommission Asset'],
    main_events: ['asset.registered', 'asset.status_changed'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [
      { type: 'overlap', description: 'Can overlap with Inventory for consumable assets.' }
    ],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-inv-001',
    slug: 'inventory',
    name: 'Inventory',
    category: 'resource',
    description: 'Stock management, materials, warehouses, and consumable items.',
    core_business: true,
    mvp_priority: 'high',
    status: 'needs_review',
    depends_on: ['organization'],
    used_by: ['work_orders', 'procurement'],
    owns_entities: ['StockItem', 'Warehouse', 'Movement'],
    does_not_own: ['Asset', 'WorkOrder'],
    main_processes: ['Receive Stock', 'Consume Stock'],
    main_events: ['stock.adjusted'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-app-001',
    slug: 'approvals',
    name: 'Approvals',
    category: 'control',
    description: 'Generic workflow blocking system for required authorizations.',
    core_business: false,
    mvp_priority: 'high',
    status: 'documented',
    depends_on: ['people', 'communication'],
    used_by: ['requests', 'procurement', 'finance'],
    owns_entities: ['ApprovalRequest', 'ApprovalFlow'],
    does_not_own: ['Request', 'User'],
    main_processes: ['Request Approval', 'Grant Approval', 'Reject Approval'],
    main_events: ['approval.granted', 'approval.rejected'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [
      { type: 'composition', description: 'Approvals block state changes but do not own the main entity.' }
    ],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-ana-001',
    slug: 'analytics',
    name: 'Analytics',
    category: 'intelligence',
    description: 'Dashboards, reporting, and data aggregation for insights.',
    core_business: false,
    mvp_priority: 'medium',
    status: 'ready_for_design',
    depends_on: ['organization'],
    used_by: [],
    owns_entities: ['Dashboard', 'Report', 'Metric'],
    does_not_own: [],
    main_processes: ['Generate Report', 'View Dashboard'],
    main_events: [],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-kno-001',
    slug: 'knowledge',
    name: 'Knowledge Base',
    category: 'information',
    description: 'Articles, wikis, standard operating procedures, and guides.',
    core_business: false,
    mvp_priority: 'medium',
    status: 'ready_for_design',
    depends_on: ['documents'],
    used_by: ['work_orders', 'requests'],
    owns_entities: ['Article', 'Category', 'FAQ'],
    does_not_own: [],
    main_processes: ['Publish Article', 'Search Knowledge'],
    main_events: ['article.published'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-cmp-001',
    slug: 'compliance',
    name: 'Compliance',
    category: 'control',
    description: 'Regulatory tracking, checklists, and normative standards enforcement.',
    core_business: false,
    mvp_priority: 'medium',
    status: 'ready_for_design',
    depends_on: ['audit', 'documents'],
    used_by: ['work_orders'],
    owns_entities: ['Policy', 'ChecklistTemplate', 'ComplianceRecord'],
    does_not_own: [],
    main_processes: ['Enforce Policy', 'Audit Check'],
    main_events: ['compliance.verified'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },

  // Future / Not MVP
  {
    id: 'cap-sal-001',
    slug: 'sales',
    name: 'Sales',
    category: 'commercial',
    description: 'CRM features, leads, opportunities, and quotes.',
    core_business: true,
    mvp_priority: 'future',
    status: 'future',
    depends_on: ['customers', 'communication'],
    used_by: ['contracts'],
    owns_entities: ['Lead', 'Opportunity', 'Quote'],
    does_not_own: ['Customer'],
    main_processes: ['Qualify Lead', 'Close Deal'],
    main_events: ['opportunity.won'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'future',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-pro-001',
    slug: 'procurement',
    name: 'Procurement',
    category: 'commercial',
    description: 'Purchase requests, supplier management, and buying processes.',
    core_business: true,
    mvp_priority: 'future',
    status: 'future',
    depends_on: ['providers', 'inventory', 'approvals'],
    used_by: ['finance'],
    owns_entities: ['PurchaseOrder', 'PurchaseRequest'],
    does_not_own: ['Provider', 'StockItem'],
    main_processes: ['Request Purchase', 'Issue PO'],
    main_events: ['po.issued'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'future',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-fin-001',
    slug: 'finance',
    name: 'Finance',
    category: 'commercial',
    description: 'Invoicing, billing, expenses, and basic financial tracking.',
    core_business: true,
    mvp_priority: 'future',
    status: 'future',
    depends_on: ['organization'],
    used_by: ['sales', 'procurement'],
    owns_entities: ['Invoice', 'Expense', 'Payment'],
    does_not_own: [],
    main_processes: ['Issue Invoice', 'Register Payment'],
    main_events: ['invoice.paid'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'future',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-ctr-001',
    slug: 'contracts',
    name: 'Contracts',
    category: 'legal',
    description: 'Lifecycle management for formal agreements and SLAs.',
    core_business: true,
    mvp_priority: 'future',
    status: 'future',
    depends_on: ['documents', 'customers', 'providers'],
    used_by: ['work_orders'],
    owns_entities: ['Contract', 'SLA', 'Term'],
    does_not_own: ['Customer', 'Provider', 'Document'],
    main_processes: ['Draft Contract', 'Sign Contract'],
    main_events: ['contract.signed'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'future',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-leg-001',
    slug: 'legal',
    name: 'Legal',
    category: 'legal',
    description: 'Disputes, compliance reviews, and legal cases.',
    core_business: false,
    mvp_priority: 'future',
    status: 'future',
    depends_on: ['documents', 'contracts'],
    used_by: [],
    owns_entities: ['LegalCase', 'Dispute'],
    does_not_own: ['Contract'],
    main_processes: ['Open Dispute', 'Resolve Case'],
    main_events: ['dispute.opened'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'future',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-prv-001',
    slug: 'providers',
    name: 'Providers',
    category: 'relationship',
    description: 'Management of external vendors, suppliers, and third parties.',
    core_business: false,
    mvp_priority: 'future',
    status: 'future',
    depends_on: ['organization'],
    used_by: ['procurement', 'contracts'],
    owns_entities: ['Provider', 'VendorCatalog'],
    does_not_own: [],
    main_processes: ['Onboard Provider', 'Evaluate Vendor'],
    main_events: ['provider.approved'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'future',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-cus-001',
    slug: 'customers',
    name: 'Customers',
    category: 'relationship',
    description: 'Management of clients, accounts, and external users.',
    core_business: false,
    mvp_priority: 'future',
    status: 'future',
    depends_on: ['organization'],
    used_by: ['sales', 'contracts', 'cases'],
    owns_entities: ['Customer', 'Account', 'Contact'],
    does_not_own: [],
    main_processes: ['Register Customer', 'Manage Account'],
    main_events: ['customer.registered'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [],
    install_state: 'future',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-cas-001',
    slug: 'cases',
    name: 'Cases',
    category: 'work-management',
    description: 'Complex, multi-step issue resolution or customer support tickets.',
    core_business: true,
    mvp_priority: 'future',
    status: 'future',
    depends_on: ['requests', 'customers'],
    used_by: [],
    owns_entities: ['Case', 'Resolution'],
    does_not_own: ['Request', 'Customer'],
    main_processes: ['Open Case', 'Resolve Case'],
    main_events: ['case.resolved'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [
      { type: 'overlap', description: 'Can overlap with generic Requests. Cases are more stateful.' }
    ],
    install_state: 'future',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  },
  {
    id: 'cap-res-001',
    slug: 'resources',
    name: 'Resources',
    category: 'resource',
    description: 'Abstract management of generic resources (rooms, vehicles, tools) beyond standard assets.',
    core_business: false,
    mvp_priority: 'future',
    status: 'blocked',
    depends_on: ['organization'],
    used_by: ['scheduling'],
    owns_entities: ['Resource', 'Booking'],
    does_not_own: [],
    main_processes: ['Book Resource', 'Release Resource'],
    main_events: ['resource.booked'],
    related_docs: [{ title: 'Universal Capability', url: '#' }],
    boundary_risk: [
      { type: 'overlap', description: 'Heavy overlap with Assets. Blocked pending definition.' }
    ],
    install_state: 'not_available',
    synthetic_notes: 'Catalogo base aguardando instalacao controlada'
  }
];
