import { ProcessGap } from './gap-tracker-types';

export const mockGaps: ProcessGap[] = [
  // Context 1: Technical Service Intake
  {
    id: 'gap-tech-001',
    pilot_id: 'pilot-tech-01',
    title: 'Missing Work Order Legacy Structure',
    description: 'The structure of the legacy work order form is not fully documented. We need the exact fields from Gestão Técnica.',
    gap_type: 'missing_source',
    severity: 'critical',
    impact: 'blocking',
    status: 'blocked_real_source',
    data_source_mode: 'real_blocked',
    owner_role: 'Technical Manager',
    required_sources: [
      { id: 'src-01', name: 'Legacy Work Order Form', description: 'PDF or screenshot of the old system' }
    ],
    missing_evidence: [],
    related_observations: [
      { id: 'obs-01', type: 'observation', title: 'Work Order Creation Step' }
    ],
    related_capabilities: [
      { id: 'cap-wo', type: 'capability', title: 'Work Order Management' }
    ],
    risk_if_missing: 'Cannot correctly map the fields for the new Builder capability.',
    next_action: 'Request real sources from the customer',
    review_decision: 'needs_real_source',
    synthetic: true,
    created_at: '2023-10-25T10:00:00Z',
    updated_at: '2023-10-25T10:00:00Z'
  },
  {
    id: 'gap-tech-002',
    pilot_id: 'pilot-tech-01',
    title: 'Unknown Approval Rule for Parts',
    description: 'We do not know the threshold for manager approval when requesting replacement parts.',
    gap_type: 'unconfirmed_rule',
    severity: 'high',
    impact: 'high',
    status: 'open',
    data_source_mode: 'synthetic',
    owner_role: 'Operations Manager',
    required_sources: [],
    missing_evidence: [
      { id: 'evd-01', name: 'Approval Policy', type: 'document', description: 'Internal policy doc' }
    ],
    related_observations: [
      { id: 'obs-02', type: 'observation', title: 'Part Request Approval' }
    ],
    related_capabilities: [
      { id: 'cap-apr', type: 'capability', title: 'Approvals Engine' }
    ],
    risk_if_missing: 'Might bypass necessary financial controls in the synthetic demo.',
    next_action: 'Simulate a generic $500 threshold for demo purposes',
    review_decision: 'usable_for_demo',
    synthetic: true,
    created_at: '2023-10-25T11:00:00Z',
    updated_at: '2023-10-26T10:00:00Z'
  },
  {
    id: 'gap-tech-003',
    pilot_id: 'pilot-tech-01',
    title: 'Customer Signature Step Missing',
    description: 'It is unclear if the customer signs digitally or physically upon service completion.',
    gap_type: 'unclear_process_step',
    severity: 'medium',
    impact: 'medium',
    status: 'pending_review',
    data_source_mode: 'mock',
    owner_role: 'Field Technician',
    required_sources: [
      { id: 'src-02', name: 'Service Completion Protocol', description: 'Protocol document' }
    ],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [
      { id: 'cap-sig', type: 'capability', title: 'Digital Signatures' }
    ],
    risk_if_missing: 'Incomplete service closure flow.',
    next_action: 'Assume digital signature for now',
    review_decision: 'not_reviewed',
    synthetic: true,
    created_at: '2023-10-26T09:00:00Z',
    updated_at: '2023-10-26T09:00:00Z'
  },
  {
    id: 'gap-tech-004',
    pilot_id: 'pilot-tech-01',
    title: 'Missing Technician App Screenshots',
    description: 'No evidence of the mobile app currently used by technicians.',
    gap_type: 'missing_evidence',
    severity: 'high',
    impact: 'medium',
    status: 'pending_source',
    data_source_mode: 'real_pending',
    owner_role: 'Field Technician',
    required_sources: [],
    missing_evidence: [
      { id: 'evd-02', name: 'Mobile App Screenshots', type: 'image', description: 'Screenshots of the legacy mobile app' }
    ],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'UX for the new technician portal might not match current expectations.',
    next_action: 'Wait for source intake completion',
    review_decision: 'needs_real_source',
    synthetic: true,
    created_at: '2023-10-27T08:00:00Z',
    updated_at: '2023-10-27T08:00:00Z'
  },
  {
    id: 'gap-tech-005',
    pilot_id: 'pilot-tech-01',
    title: 'SLA Calculation Formula',
    description: 'The exact formula for SLA calculation is not confirmed.',
    gap_type: 'unconfirmed_rule',
    severity: 'low',
    impact: 'low',
    status: 'reviewed_synthetic',
    data_source_mode: 'synthetic',
    owner_role: 'Service Desk',
    required_sources: [],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'Minor discrepancy in reporting.',
    next_action: 'Use standard 48h SLA for synthetic demo',
    review_decision: 'synthetic_only',
    synthetic: true,
    created_at: '2023-10-27T10:00:00Z',
    updated_at: '2023-10-28T10:00:00Z'
  },
  {
    id: 'gap-tech-006',
    pilot_id: 'pilot-tech-01',
    title: 'Ambiguous Escalation Owner',
    description: 'When SLA breaches, it is ambiguous who the ticket escalates to.',
    gap_type: 'ambiguous_owner',
    severity: 'medium',
    impact: 'medium',
    status: 'open',
    data_source_mode: 'mock',
    owner_role: 'Service Desk',
    required_sources: [],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'Escalation workflow cannot be fully modeled.',
    next_action: 'Map to default Service Manager role',
    review_decision: 'not_reviewed',
    synthetic: true,
    created_at: '2023-10-28T09:00:00Z',
    updated_at: '2023-10-28T09:00:00Z'
  },

  // Context 2: Clinic Appointment Intake
  {
    id: 'gap-clinic-001',
    pilot_id: 'pilot-clinic-01',
    title: 'Patient Intake Form Missing',
    description: 'We need the standard intake form used at the front desk.',
    gap_type: 'missing_source',
    severity: 'high',
    impact: 'high',
    status: 'pending_source',
    data_source_mode: 'real_pending',
    owner_role: 'Receptionist',
    required_sources: [
      { id: 'src-03', name: 'Intake Form Template', description: 'Blank PDF of the intake form' }
    ],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'Cannot model the initial patient data capture.',
    next_action: 'Follow up with clinic manager',
    review_decision: 'needs_real_source',
    synthetic: true,
    created_at: '2023-10-20T08:00:00Z',
    updated_at: '2023-10-20T08:00:00Z'
  },
  {
    id: 'gap-clinic-002',
    pilot_id: 'pilot-clinic-01',
    title: 'Privacy Risk on Symptom Capture',
    description: 'The current mock captures symptoms directly in a non-secure text field.',
    gap_type: 'privacy_risk',
    severity: 'critical',
    impact: 'blocking',
    status: 'open',
    data_source_mode: 'synthetic',
    owner_role: 'Compliance Officer',
    required_sources: [],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'HIPAA/LGPD violation if built without secure fields.',
    next_action: 'Review data privacy guidelines for health data',
    review_decision: 'needs_validation',
    synthetic: true,
    created_at: '2023-10-21T09:00:00Z',
    updated_at: '2023-10-21T09:00:00Z'
  },
  {
    id: 'gap-clinic-003',
    pilot_id: 'pilot-clinic-01',
    title: 'No Show Policy Confirmation',
    description: 'Policy for handling patient no-shows is not confirmed.',
    gap_type: 'unconfirmed_rule',
    severity: 'low',
    impact: 'low',
    status: 'reviewed_synthetic',
    data_source_mode: 'mock',
    owner_role: 'Clinic Manager',
    required_sources: [],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'Inaccurate scheduling mock.',
    next_action: 'Assume auto-cancel after 15 mins for demo',
    review_decision: 'synthetic_only',
    synthetic: true,
    created_at: '2023-10-22T10:00:00Z',
    updated_at: '2023-10-22T10:00:00Z'
  },
  {
    id: 'gap-clinic-004',
    pilot_id: 'pilot-clinic-01',
    title: 'Insurance Validation Step',
    description: 'How is insurance validated currently?',
    gap_type: 'unclear_process_step',
    severity: 'medium',
    impact: 'high',
    status: 'open',
    data_source_mode: 'mixed',
    owner_role: 'Billing Specialist',
    required_sources: [],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'Billing flow cannot be tested.',
    next_action: 'Create mock insurance provider API response',
    review_decision: 'not_reviewed',
    synthetic: true,
    created_at: '2023-10-23T11:00:00Z',
    updated_at: '2023-10-23T11:00:00Z'
  },
  {
    id: 'gap-clinic-005',
    pilot_id: 'pilot-clinic-01',
    title: 'Missing Consent Form',
    description: 'Patient consent form is missing from the intake process.',
    gap_type: 'missing_consent',
    severity: 'high',
    impact: 'high',
    status: 'open',
    data_source_mode: 'synthetic',
    owner_role: 'Legal',
    required_sources: [
       { id: 'src-04', name: 'Consent Form', description: 'Standard consent form' }
    ],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'Legal compliance issue.',
    next_action: 'Generate a generic consent form for demo',
    review_decision: 'usable_for_demo',
    synthetic: true,
    created_at: '2023-10-24T10:00:00Z',
    updated_at: '2023-10-24T10:00:00Z'
  },
  {
    id: 'gap-clinic-006',
    pilot_id: 'pilot-clinic-01',
    title: 'Doctor Schedule Format',
    description: 'Unknown format for importing doctor schedules.',
    gap_type: 'unknown_legacy_field',
    severity: 'medium',
    impact: 'medium',
    status: 'deferred',
    data_source_mode: 'synthetic',
    owner_role: 'IT Admin',
    required_sources: [],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'Manual entry required for schedules.',
    next_action: 'Use manual entry for demo',
    review_decision: 'synthetic_only',
    synthetic: true,
    created_at: '2023-10-25T09:00:00Z',
    updated_at: '2023-10-25T09:00:00Z'
  },

  // Context 3: Workshop Repair Intake
  {
    id: 'gap-work-001',
    pilot_id: 'pilot-work-01',
    title: 'Vehicle Inspection Checklist',
    description: 'Missing the 20-point inspection checklist used by mechanics.',
    gap_type: 'missing_source',
    severity: 'high',
    impact: 'high',
    status: 'pending_source',
    data_source_mode: 'real_pending',
    owner_role: 'Lead Mechanic',
    required_sources: [
      { id: 'src-05', name: 'Inspection Checklist', description: 'Paper form used in shop' }
    ],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'Cannot build the inspection digital form.',
    next_action: 'Request checklist from shop manager',
    review_decision: 'needs_real_source',
    synthetic: true,
    created_at: '2023-10-15T08:00:00Z',
    updated_at: '2023-10-15T08:00:00Z'
  },
  {
    id: 'gap-work-002',
    pilot_id: 'pilot-work-01',
    title: 'Parts Inventory Integration',
    description: 'Unclear if we need to integrate with legacy parts system or just mock it.',
    gap_type: 'unconfirmed_rule',
    severity: 'medium',
    impact: 'medium',
    status: 'open',
    data_source_mode: 'mixed',
    owner_role: 'Inventory Manager',
    required_sources: [],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'Inventory counts might be inaccurate.',
    next_action: 'Mock inventory for phase 1',
    review_decision: 'usable_for_demo',
    synthetic: true,
    created_at: '2023-10-16T09:00:00Z',
    updated_at: '2023-10-16T09:00:00Z'
  },
  {
    id: 'gap-work-003',
    pilot_id: 'pilot-work-01',
    title: 'Photo Evidence Storage',
    description: 'Mechanics take photos of damage. Where are these stored today?',
    gap_type: 'unclear_process_step',
    severity: 'medium',
    impact: 'low',
    status: 'reviewed_synthetic',
    data_source_mode: 'synthetic',
    owner_role: 'Mechanic',
    required_sources: [],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'No centralized photo storage.',
    next_action: 'Include standard file upload in mock',
    review_decision: 'synthetic_only',
    synthetic: true,
    created_at: '2023-10-17T10:00:00Z',
    updated_at: '2023-10-17T10:00:00Z'
  },
  {
    id: 'gap-work-004',
    pilot_id: 'pilot-work-01',
    title: 'Customer Approval Workflow',
    description: 'How does the customer approve additional repair costs?',
    gap_type: 'ambiguous_owner',
    severity: 'high',
    impact: 'high',
    status: 'open',
    data_source_mode: 'mock',
    owner_role: 'Service Advisor',
    required_sources: [],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'Repairs might be done without approval.',
    next_action: 'Build SMS approval mock',
    review_decision: 'usable_for_demo',
    synthetic: true,
    created_at: '2023-10-18T11:00:00Z',
    updated_at: '2023-10-18T11:00:00Z'
  },
  {
    id: 'gap-work-005',
    pilot_id: 'pilot-work-01',
    title: 'Missing Damage Codes',
    description: 'We don\'t have the list of standard damage codes.',
    gap_type: 'unknown_legacy_field',
    severity: 'low',
    impact: 'low',
    status: 'deferred',
    data_source_mode: 'synthetic',
    owner_role: 'System Admin',
    required_sources: [],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'Free text entry instead of standardized codes.',
    next_action: 'Use free text for demo',
    review_decision: 'synthetic_only',
    synthetic: true,
    created_at: '2023-10-19T09:00:00Z',
    updated_at: '2023-10-19T09:00:00Z'
  },
  {
    id: 'gap-work-006',
    pilot_id: 'pilot-work-01',
    title: 'Payment Processing Missing',
    description: 'No documentation on how final payment is processed.',
    gap_type: 'missing_source',
    severity: 'critical',
    impact: 'blocking',
    status: 'blocked_real_source',
    data_source_mode: 'real_blocked',
    owner_role: 'Finance',
    required_sources: [
       { id: 'src-06', name: 'Payment Gateway Docs', description: 'API docs for payment terminal' }
    ],
    missing_evidence: [],
    related_observations: [],
    related_capabilities: [],
    risk_if_missing: 'Cannot close the ticket completely.',
    next_action: 'Block until docs are provided',
    review_decision: 'needs_real_source',
    synthetic: true,
    created_at: '2023-10-20T10:00:00Z',
    updated_at: '2023-10-20T10:00:00Z'
  }
];
