import { AsIsProcessMirror } from './as-is-mirror-types';

export const MOCK_ACTOR_ROLES = {
  requester: { id: 'role-1', name: 'Requester (Client)', type: 'external' as const },
  dispatcher: { id: 'role-2', name: 'Dispatcher', type: 'internal' as const },
  technician: { id: 'role-3', name: 'Technician', type: 'internal' as const },
  supervisor: { id: 'role-4', name: 'Supervisor', type: 'internal' as const },
  receptionist: { id: 'role-5', name: 'Receptionist', type: 'internal' as const },
  doctor: { id: 'role-6', name: 'Doctor', type: 'internal' as const },
  mechanic: { id: 'role-7', name: 'Mechanic', type: 'internal' as const },
};

export const MOCK_DATA_POINTS = {
  msg_whatsapp: { id: 'dp-1', name: 'WhatsApp Message', type: 'verbal' as const, description: 'Initial contact message' },
  photo_problem: { id: 'dp-2', name: 'Problem Photo', type: 'document' as const, description: 'Photo of the broken equipment' },
  spreadsheet_row: { id: 'dp-3', name: 'Control Sheet Row', type: 'data_field' as const },
  formal_os: { id: 'dp-4', name: 'Service Order Record', type: 'data_field' as const },
  completion_photo: { id: 'dp-5', name: 'Completion Photo', type: 'document' as const },
  verbal_ok: { id: 'dp-6', name: 'Verbal OK', type: 'verbal' as const },
};

export const MOCK_MIRRORS: AsIsProcessMirror[] = [
  {
    id: 'mirror-tech-service',
    title: 'Technical Service Intake',
    slug: 'tech-service-intake',
    description: 'Processo de triagem e envio de técnicos para manutenção. (SYNTHETIC DEMO - NOT RUNTIME WORKFLOW - REAL SOURCES PENDING)',
    process_area: 'Technical Support',
    data_source_mode: 'synthetic',
    validation_status: 'synthetic_only',
    confidence: 'low',
    synthetic: true,
    steps: [
      {
        id: 'step-1',
        sequence: 1,
        title: 'Customer reports issue',
        description: 'Cliente envia mensagem via WhatsApp relatando um problema.',
        step_type: 'intake',
        actor_role: MOCK_ACTOR_ROLES.requester.id,
        input_refs: [],
        output_refs: [MOCK_DATA_POINTS.msg_whatsapp.id],
        system_touchpoints: [{ id: 'sys-wa', name: 'WhatsApp', type: 'chat' }],
        document_touchpoints: [],
        evidence_refs: [{ id: 'ev-1', title: 'Synthetic Chat Log', type: 'observation_note' }],
        gap_refs: [],
        risk_flags: [],
        capability_candidates: [{ id: 'cap-req', capability_key: 'requests', reasoning: 'Could formalize intake.' }],
        data_source_mode: 'synthetic',
        confidence: 'medium',
        validation_status: 'synthetic_only',
        synthetic: true,
      },
      {
        id: 'step-2',
        sequence: 2,
        title: 'Dispatcher triage',
        description: 'Atendente lê a mensagem e avalia se precisa de foto.',
        step_type: 'triage',
        actor_role: MOCK_ACTOR_ROLES.dispatcher.id,
        input_refs: [MOCK_DATA_POINTS.msg_whatsapp.id],
        output_refs: [],
        system_touchpoints: [],
        document_touchpoints: [],
        evidence_refs: [],
        gap_refs: [{ id: 'gap-triage', title: 'No formal triage criteria', description: 'Triage is based on dispatcher experience.', severity: 'high' }],
        risk_flags: [{ id: 'risk-delay', title: 'Response Delay', description: 'WhatsApp queue can cause missed messages.', impact: 'medium' }],
        capability_candidates: [],
        data_source_mode: 'synthetic',
        confidence: 'low',
        validation_status: 'needs_real_validation',
        synthetic: true,
      },
      {
        id: 'step-3',
        sequence: 3,
        title: 'Register in Spreadsheet',
        description: 'Atendente copia dados para planilha de controle (Shadow IT).',
        step_type: 'documentation',
        actor_role: MOCK_ACTOR_ROLES.dispatcher.id,
        input_refs: [MOCK_DATA_POINTS.msg_whatsapp.id],
        output_refs: [MOCK_DATA_POINTS.spreadsheet_row.id],
        system_touchpoints: [{ id: 'sys-sheet', name: 'Google Sheets', type: 'spreadsheet' }],
        document_touchpoints: [],
        evidence_refs: [{ id: 'ev-2', title: 'Spreadsheet Screenshot (Mock)', type: 'screenshot' }],
        gap_refs: [{ id: 'gap-shadow-it', title: 'Shadow IT Usage', description: 'Spreadsheet is used instead of system.', severity: 'high' }],
        risk_flags: [],
        capability_candidates: [{ id: 'cap-board', capability_key: 'work_board', reasoning: 'Replace spreadsheet with tracked board.' }],
        data_source_mode: 'real_pending',
        confidence: 'low',
        validation_status: 'blocked_real_sources',
        synthetic: true,
      },
      {
        id: 'step-4',
        sequence: 4,
        title: 'Create OS in Legacy System',
        description: 'Atendente cadastra a OS formal no sistema antigo.',
        step_type: 'execution',
        actor_role: MOCK_ACTOR_ROLES.dispatcher.id,
        input_refs: [MOCK_DATA_POINTS.spreadsheet_row.id],
        output_refs: [MOCK_DATA_POINTS.formal_os.id],
        system_touchpoints: [{ id: 'sys-legacy', name: 'Legacy ERP', type: 'system' }],
        document_touchpoints: [],
        evidence_refs: [],
        gap_refs: [],
        risk_flags: [],
        capability_candidates: [{ id: 'cap-wo', capability_key: 'work_orders', reasoning: 'Core work order generation.' }],
        data_source_mode: 'mock',
        confidence: 'medium',
        validation_status: 'synthetic_only',
        synthetic: true,
      },
      {
        id: 'step-5',
        sequence: 5,
        title: 'Notify Technician',
        description: 'Atendente avisa técnico via WhatsApp que há uma nova OS.',
        step_type: 'notification',
        actor_role: MOCK_ACTOR_ROLES.dispatcher.id,
        input_refs: [MOCK_DATA_POINTS.formal_os.id],
        output_refs: [],
        system_touchpoints: [{ id: 'sys-wa2', name: 'WhatsApp', type: 'chat' }],
        document_touchpoints: [],
        evidence_refs: [],
        gap_refs: [{ id: 'gap-handoff', title: 'Informal Handoff', description: 'Technician might miss the message.', severity: 'high' }],
        risk_flags: [{ id: 'risk-comm', title: 'Lost Communication', description: 'No trace of assignment acceptance.', impact: 'high' }],
        capability_candidates: [{ id: 'cap-notif', capability_key: 'communications', reasoning: 'Systematic dispatch.' }],
        data_source_mode: 'mixed',
        confidence: 'conflicting',
        validation_status: 'needs_real_validation',
        synthetic: true,
      },
      {
        id: 'step-6',
        sequence: 6,
        title: 'Complete and Validate',
        description: 'Técnico manda foto do conserto e Supervisor fecha OS no sistema.',
        step_type: 'closure',
        actor_role: MOCK_ACTOR_ROLES.technician.id,
        input_refs: [],
        output_refs: [MOCK_DATA_POINTS.completion_photo.id],
        system_touchpoints: [{ id: 'sys-legacy', name: 'Legacy ERP', type: 'system' }],
        document_touchpoints: [],
        evidence_refs: [{ id: 'ev-3', title: 'Mock Completion Photo', type: 'document' }],
        gap_refs: [],
        risk_flags: [],
        capability_candidates: [{ id: 'cap-appr', capability_key: 'approvals', reasoning: 'Supervisor validation.' }],
        data_source_mode: 'real_blocked',
        confidence: 'unknown',
        validation_status: 'blocked_real_sources',
        synthetic: true,
      }
    ],
    handoffs: [
      {
        id: 'ho-1',
        from_role_id: MOCK_ACTOR_ROLES.requester.id,
        to_role_id: MOCK_ACTOR_ROLES.dispatcher.id,
        method: 'WhatsApp Chat',
        artifacts_passed: [MOCK_DATA_POINTS.msg_whatsapp.id]
      },
      {
        id: 'ho-2',
        from_role_id: MOCK_ACTOR_ROLES.dispatcher.id,
        to_role_id: MOCK_ACTOR_ROLES.technician.id,
        method: 'Verbal / WhatsApp',
        artifacts_passed: [MOCK_DATA_POINTS.formal_os.id]
      }
    ],
    gap_overlays: [],
    capability_candidates: [],
    related_sources: [],
    related_evidence: [],
    related_observations: [],
    related_docs: [],
  },
  {
    id: 'mirror-clinic',
    title: 'Clinic Appointment Intake',
    slug: 'clinic-appointment',
    description: 'Processo sintético de agendamento de clínica.',
    process_area: 'Healthcare Admin',
    data_source_mode: 'synthetic',
    validation_status: 'not_reviewed',
    confidence: 'medium',
    synthetic: true,
    steps: [
      {
        id: 'c-step-1',
        sequence: 1,
        title: 'Patient calls',
        description: 'Paciente liga para marcar consulta.',
        step_type: 'intake',
        actor_role: MOCK_ACTOR_ROLES.requester.id,
        input_refs: [],
        output_refs: [],
        system_touchpoints: [{ id: 'sys-phone', name: 'Phone', type: 'other' }],
        document_touchpoints: [],
        evidence_refs: [],
        gap_refs: [],
        risk_flags: [],
        capability_candidates: [],
        data_source_mode: 'synthetic',
        confidence: 'high',
        validation_status: 'synthetic_only',
        synthetic: true,
      },
      {
        id: 'c-step-2',
        sequence: 2,
        title: 'Check availability',
        description: 'Recepcionista olha agenda de papel e sistema.',
        step_type: 'triage',
        actor_role: MOCK_ACTOR_ROLES.receptionist.id,
        input_refs: [],
        output_refs: [],
        system_touchpoints: [{ id: 'sys-paper', name: 'Paper Agenda', type: 'paper' }],
        document_touchpoints: [],
        evidence_refs: [],
        gap_refs: [{ id: 'gap-c-sync', title: 'Double booking risk', description: 'Paper and system not synced', severity: 'high' }],
        risk_flags: [],
        capability_candidates: [{ id: 'cap-sched', capability_key: 'scheduling', reasoning: 'Unified calendar needed.' }],
        data_source_mode: 'synthetic',
        confidence: 'medium',
        validation_status: 'synthetic_only',
        synthetic: true,
      },
      {
        id: 'c-step-3',
        sequence: 3,
        title: 'Confirm slot',
        description: 'Confirma horário verbalmente.',
        step_type: 'decision',
        actor_role: MOCK_ACTOR_ROLES.receptionist.id,
        input_refs: [],
        output_refs: [MOCK_DATA_POINTS.verbal_ok.id],
        system_touchpoints: [],
        document_touchpoints: [],
        evidence_refs: [],
        gap_refs: [],
        risk_flags: [],
        capability_candidates: [],
        data_source_mode: 'synthetic',
        confidence: 'high',
        validation_status: 'synthetic_only',
        synthetic: true,
      },
      {
        id: 'c-step-4',
        sequence: 4,
        title: 'Enter in System',
        description: 'Registra no software.',
        step_type: 'execution',
        actor_role: MOCK_ACTOR_ROLES.receptionist.id,
        input_refs: [],
        output_refs: [],
        system_touchpoints: [{ id: 'sys-clinic', name: 'Clinic Software', type: 'system' }],
        document_touchpoints: [],
        evidence_refs: [],
        gap_refs: [],
        risk_flags: [],
        capability_candidates: [],
        data_source_mode: 'synthetic',
        confidence: 'high',
        validation_status: 'synthetic_only',
        synthetic: true,
      },
      {
        id: 'c-step-5',
        sequence: 5,
        title: 'Doctor sees schedule',
        description: 'Médico olha agenda no dia.',
        step_type: 'execution',
        actor_role: MOCK_ACTOR_ROLES.doctor.id,
        input_refs: [],
        output_refs: [],
        system_touchpoints: [{ id: 'sys-clinic', name: 'Clinic Software', type: 'system' }],
        document_touchpoints: [],
        evidence_refs: [],
        gap_refs: [],
        risk_flags: [],
        capability_candidates: [],
        data_source_mode: 'synthetic',
        confidence: 'medium',
        validation_status: 'synthetic_only',
        synthetic: true,
      },
      {
        id: 'c-step-6',
        sequence: 6,
        title: 'Patient arrives',
        description: 'Paciente chega para consulta.',
        step_type: 'closure',
        actor_role: MOCK_ACTOR_ROLES.receptionist.id,
        input_refs: [],
        output_refs: [],
        system_touchpoints: [],
        document_touchpoints: [],
        evidence_refs: [],
        gap_refs: [],
        risk_flags: [],
        capability_candidates: [],
        data_source_mode: 'synthetic',
        confidence: 'high',
        validation_status: 'synthetic_only',
        synthetic: true,
      }
    ],
    handoffs: [],
    gap_overlays: [],
    capability_candidates: [],
    related_sources: [],
    related_evidence: [],
    related_observations: [],
    related_docs: [],
  },
  {
    id: 'mirror-workshop',
    title: 'Workshop Repair Intake',
    slug: 'workshop-repair',
    description: 'Processo sintético de recebimento de equipamento em oficina.',
    process_area: 'Maintenance',
    data_source_mode: 'synthetic',
    validation_status: 'synthetic_only',
    confidence: 'high',
    synthetic: true,
    steps: [
      { id: 'w-1', sequence: 1, title: 'Drop off', description: 'Cliente deixa item.', step_type: 'intake', actor_role: MOCK_ACTOR_ROLES.requester.id, input_refs: [], output_refs: [], system_touchpoints: [], document_touchpoints: [], evidence_refs: [], gap_refs: [], risk_flags: [], capability_candidates: [], data_source_mode: 'synthetic', confidence: 'high', validation_status: 'synthetic_only', synthetic: true },
      { id: 'w-2', sequence: 2, title: 'Write paper ticket', description: 'Preenche ordem de papel.', step_type: 'documentation', actor_role: MOCK_ACTOR_ROLES.receptionist.id, input_refs: [], output_refs: [], system_touchpoints: [], document_touchpoints: [], evidence_refs: [], gap_refs: [], risk_flags: [], capability_candidates: [], data_source_mode: 'synthetic', confidence: 'high', validation_status: 'synthetic_only', synthetic: true },
      { id: 'w-3', sequence: 3, title: 'Give ticket copy', description: 'Entrega via do cliente.', step_type: 'handoff', actor_role: MOCK_ACTOR_ROLES.receptionist.id, input_refs: [], output_refs: [], system_touchpoints: [], document_touchpoints: [], evidence_refs: [], gap_refs: [], risk_flags: [], capability_candidates: [], data_source_mode: 'synthetic', confidence: 'high', validation_status: 'synthetic_only', synthetic: true },
      { id: 'w-4', sequence: 4, title: 'Place item on shelf', description: 'Guarda item na prateleira de entrada.', step_type: 'execution', actor_role: MOCK_ACTOR_ROLES.receptionist.id, input_refs: [], output_refs: [], system_touchpoints: [], document_touchpoints: [], evidence_refs: [], gap_refs: [], risk_flags: [], capability_candidates: [], data_source_mode: 'synthetic', confidence: 'high', validation_status: 'synthetic_only', synthetic: true },
      { id: 'w-5', sequence: 5, title: 'Mechanic picks up', description: 'Mecânico pega item da prateleira.', step_type: 'execution', actor_role: MOCK_ACTOR_ROLES.mechanic.id, input_refs: [], output_refs: [], system_touchpoints: [], document_touchpoints: [], evidence_refs: [], gap_refs: [], risk_flags: [], capability_candidates: [], data_source_mode: 'synthetic', confidence: 'high', validation_status: 'synthetic_only', synthetic: true },
      { id: 'w-6', sequence: 6, title: 'Starts diagnosis', description: 'Inicia diagnóstico técnico.', step_type: 'execution', actor_role: MOCK_ACTOR_ROLES.mechanic.id, input_refs: [], output_refs: [], system_touchpoints: [], document_touchpoints: [], evidence_refs: [], gap_refs: [], risk_flags: [], capability_candidates: [], data_source_mode: 'synthetic', confidence: 'high', validation_status: 'synthetic_only', synthetic: true }
    ],
    handoffs: [],
    gap_overlays: [],
    capability_candidates: [],
    related_sources: [],
    related_evidence: [],
    related_observations: [],
    related_docs: [],
  }
];
