import { RegistryItem } from './registry-types';

export const mockRegistryData: RegistryItem[] = [
  {
    id: 'cap-org',
    name: 'Organization Capability',
    slug: 'organization',
    type: 'capability',
    description: 'Gerencia a estrutura organizacional e workspaces do sistema.',
    status: 'needs_review',
    source_document: 'CAPABILITY_REGISTRY.md',
    depends_on: [],
    used_by: ['people', 'customers', 'providers'],
    rules: ['ORG-RULE-001', 'ORG-RULE-002'],
    document_links: [
      { label: 'Universal Entity Model', url: '/docs/capabilities/universal/organization' },
    ],
    risk_level: 'low',
    notes: 'Capability foundational. Requer validação piloto.',
    synthetic: true,
  },
  {
    id: 'cap-req',
    name: 'Requests Capability',
    slug: 'requests',
    type: 'capability',
    description: 'Gestão de entradas e demandas operacionais não-estruturadas.',
    status: 'needs_review',
    source_document: 'CAPABILITY_REGISTRY.md',
    related_capability: 'work_orders',
    depends_on: ['customers', 'communication'],
    used_by: ['cases', 'work_orders'],
    rules: ['REQ-RULE-001'],
    document_links: [],
    risk_level: 'medium',
    synthetic: true,
  },
  {
    id: 'rule-001',
    name: 'Registry Read-Only Rule',
    slug: 'registry-readonly-rule',
    type: 'dependency_rule',
    description: 'Registry View não deve alterar capabilities.',
    status: 'documented',
    source_document: 'DEPENDENCY_RULES.md',
    related_capability: 'capability_registry',
    depends_on: [],
    used_by: ['builder_shell'],
    rules: [],
    document_links: [],
    risk_level: 'low',
    synthetic: true,
  },
  {
    id: 'model-process-01',
    name: 'Universal Process Model',
    slug: 'universal-process-model',
    type: 'process_model',
    description: 'Contrato padrão para mapeamento e execução de processos.',
    status: 'documented',
    source_document: 'UNIVERSAL_PROCESS_MODEL.md',
    depends_on: [],
    used_by: ['workflow_builder'],
    rules: [],
    document_links: [
      { label: 'Process Model Doc', url: '/docs/capabilities/UNIVERSAL_PROCESS_MODEL.md' },
    ],
    risk_level: 'high',
    notes: 'Crítico para o motor de Runtime',
    synthetic: true,
  },
  {
    id: 'view-explorer',
    name: 'Capability Explorer UI',
    slug: 'capability-explorer-view',
    type: 'view_contract',
    description: 'Interface de navegação e simulação do catálogo de capacidades.',
    status: 'ready_for_design',
    source_document: 'CAPABILITY_EXPLORER.md',
    depends_on: ['capability_model'],
    used_by: ['builder_shell'],
    rules: [],
    document_links: [],
    risk_level: 'low',
    synthetic: true,
  },
  {
    id: 'dec-001',
    name: 'System Builder Platform First',
    slug: 'dec-sb-001',
    type: 'decision',
    description: 'Priorizar o desenvolvimento agnóstico da plataforma antes dos fluxos do piloto.',
    status: 'documented',
    source_document: 'DEC-SB-001.md',
    depends_on: [],
    used_by: ['all'],
    rules: [],
    document_links: [],
    risk_level: 'medium',
    notes: 'Decisão arquitetural principal do projeto no momento.',
    synthetic: true,
  },
];
