import { z } from "zod";

export const workPackageSchema = z.object({
  key: z.string().min(1),
  title: z.string().min(1),
  moduleKey: z.string().min(1),
  laneKey: z.string().min(1),
  workerRole: z.string().min(1),
  waveKey: z.string().min(1),
  packageSize: z.string().min(1),
  priority: z.number().int(),
  status: z.enum(["planned", "in_progress", "done", "blocked"]),
  objective: z.string().min(1),
  expectedOutcome: z.string().min(1),
  entryGate: z.string().nullable().optional(),
  exitGate: z.string().nullable().optional(),
  baseBranch: z.string().min(1),
  baseSha: z.string().min(1),
  targetBranch: z.string().min(1),
  integrationBranch: z.string().min(1),
  ownedPaths: z.array(z.string()),
  readOnlyPaths: z.array(z.string()),
  forbiddenPaths: z.array(z.string()),
  readFirst: z.array(z.string()),
  requiredTests: z.array(z.string()),
  acceptanceCriteria: z.array(z.string()),
  documentationImpacts: z.array(z.string()),
  integrationRisk: z.string(),
  mergeOrder: z.number().int(),
  rollbackNotes: z.string().nullable().optional(),
  assignedWorkerKey: z.string().nullable().optional(),
  revision: z.number().int().default(1),
});
