import type { WorkspaceModuleConfig } from "./types";

export const ecosystemModules: WorkspaceModuleConfig[] = [
  {
    key: "events",
    name: "Eventos",
    description: "Memoria operacional, auditoria, timeline e historico por entidade.",
    layer: "platform",
    status: "implemented",
  },
  {
    key: "workflow-engine",
    name: "Workflow",
    description: "Estados, transicoes e governanca de execucao dos fluxos.",
    layer: "platform",
    status: "planned",
  },
  {
    key: "documents",
    name: "Documentos",
    description: "Templates, evidencias, relatorios tecnicos e aprovacao documental.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "work-items",
    name: "Demandas",
    description: "Envelope universal de entrada, triagem e priorizacao.",
    layer: "module",
    status: "adjusted",
  },
  {
    key: "service-orders",
    name: "Ordens de Servico",
    description: "Execucao autorizada de mao de obra, tempo, evidencias e aprovacao.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "assets",
    name: "Ativos",
    description: "Equipamentos, infraestrutura, sistemas e historico operacional.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "workforce",
    name: "Mao de Obra",
    description: "Equipes, perfis tecnicos, papeis e disponibilidade.",
    layer: "module",
    status: "adjusted",
  },
  {
    key: "scheduling",
    name: "Escalas",
    description: "Expediente, plantao, sobreaviso, ausencias e capacidade planejada.",
    layer: "module",
    status: "adjusted",
  },
  {
    key: "shifts",
    name: "Livro de Turno",
    description: "Passagem de servico, pendencias e ocorrencias do turno.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "legacy",
    name: "Legado",
    description: "Protocolos, status externo e ponte manual-primeiro com sistema oficial.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "approvals",
    name: "Revisão Técnica",
    description: "Fluxos de aprovação, aceite e retorno técnico de execuções.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "notifications",
    name: "Notificações",
    description: "Alertas e avisos automáticos por papel ou usuário.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "reports",
    name: "Relatórios",
    description: "Leitura analítica e sumarização de dados operacionais.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "maintenance-plans",
    name: "Planos de Manutenção",
    description: "Planejamento preventivo por ativo, período e criticidade.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "dashboard",
    name: "Dashboard",
    description: "Visão executiva e indicadores de performance (KPIs).",
    layer: "module",
    status: "implemented",
  },
  {
    key: "global-search",
    name: "Busca Global",
    description: "Localização rápida de qualquer entidade do sistema.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "automations",
    name: "Automações",
    description: "Registro governado de gatilhos, endpoints e rotinas de integração.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "evidences",
    name: "Evidências",
    description: "Biblioteca de comprovantes, fotos, documentos e links técnicos.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "secao-tecnica",
    name: "Adaptacao Secao Tecnica",
    description: "Vocabulario, tipos, filas, papeis, workflows e templates do cliente.",
    layer: "adaptation",
    status: "implemented",
  },
];
