import type { WorkspaceModuleConfig } from "./types";

export const ecosystemModules: WorkspaceModuleConfig[] = [
  {
    key: "events",
    name: "Eventos",
    description: "Memória operacional, auditoria, timeline e histórico por entidade.",
    layer: "platform",
    status: "implemented",
  },
  {
    key: "workflow-engine",
    name: "Workflow",
    description: "Estados, transições e governança de execução dos fluxos.",
    layer: "platform",
    status: "planned",
  },
  {
    key: "documents",
    name: "Documentos",
    description: "Templates, evidências, relatórios e aprovação documental.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "work-items",
    name: "Demandas",
    description: "Envelope universal de entrada, triagem e priorização.",
    layer: "module",
    status: "adjusted",
  },
  {
    key: "service-orders",
    name: "Ordens de Serviço",
    description: "Execução autorizada de trabalho, tempo, evidências e aprovação.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "assets",
    name: "Ativos",
    description: "Equipamentos, infraestrutura, sistemas e histórico operacional.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "workforce",
    name: "Workforce",
    description: "Equipes, perfis, papéis e disponibilidade.",
    layer: "module",
    status: "adjusted",
  },
  {
    key: "scheduling",
    name: "Escalas",
    description: "Expediente, plantão, sobreaviso, ausências e capacidade planejada.",
    layer: "module",
    status: "adjusted",
  },
  {
    key: "shifts",
    name: "Livro de Turno",
    description: "Passagem de serviço, pendências e ocorrências do turno.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "legacy",
    name: "Legado",
    description: "Protocolos, status externo e ponte manual-primeiro com sistema oficial.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "approvals",
    name: "Revisão Operacional",
    description: "Fluxos de aprovação, aceite e retorno responsável de execuções.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "notifications",
    name: "Notificações",
    description: "Alertas e avisos automáticos por papel ou usuário.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "reports",
    name: "Relatórios",
    description: "Leitura analítica e sumarização de dados operacionais.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "maintenance-plans",
    name: "Planos de Manutenção",
    description: "Planejamento preventivo por ativo, período e criticidade.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "dashboard",
    name: "Dashboard",
    description: "Visão executiva e indicadores de performance (KPIs).",
    layer: "module",
    status: "implemented",
  },
  {
    key: "global-search",
    name: "Busca Global",
    description: "Localização rápida de qualquer entidade do sistema.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "automations",
    name: "Automações",
    description: "Registro governado de gatilhos, endpoints e rotinas de integração.",
    layer: "module",
    status: "implemented",
  },
  {
    key: "evidences",
    name: "Evidências",
    description: "Biblioteca de comprovantes, fotos, documentos e links responsávels.",
    layer: "module",
    status: "implemented",
  },
];
