import { TaskItem, TaskGroup, TaskStatus, TaskPriority } from "./tasker-types";

const now = new Date().toISOString();

export const MOCK_TASKS: TaskItem[] = [
  {
    id: "BUILDER-SHELL-001",
    title: "Planejar shell principal do System Builder",
    module: "ui",
    group: "A",
    type: "architecture",
    priority: "high",
    status: "done",
    summary: "Contrato e planejamento do Shell aprovados",
    depends_on: [],
    blocked_by: [],
    expected_files: ["docs/ui/surfaces/BUILDER_SHELL.md"],
    acceptance_criteria: ["Contrato documentado"],
    evidence: [
      { id: "e1", name: "BUILDER_SHELL.md", filePath: "docs/ui/surfaces/BUILDER_SHELL.md", provided: true }
    ],
    created_at: now,
    updated_at: now,
    source_docs: [],
    next_action: "None",
    is_synthetic: true
  },
  {
    id: "DEV-READINESS-BUILDER-SHELL-001",
    title: "Auditar prontidão para desenvolvimento do Builder Shell",
    module: "tasker",
    group: "A",
    type: "architecture",
    priority: "high",
    status: "done",
    summary: "Contrato auditado e autorizado para dev",
    depends_on: [{ taskId: "BUILDER-SHELL-001", relationship: "depends_on" }],
    blocked_by: [],
    expected_files: ["docs/ui/reviews/DEV-READINESS-BUILDER-SHELL-001_AUDIT.md"],
    acceptance_criteria: ["Auditoria concluída"],
    evidence: [
      { id: "e2", name: "Audit Report", filePath: "docs/ui/reviews/DEV-READINESS-BUILDER-SHELL-001_AUDIT.md", provided: true }
    ],
    created_at: now,
    updated_at: now,
    source_docs: [],
    next_action: "None",
    is_synthetic: true
  },
  {
    id: "DEV-BUILDER-SHELL-001",
    title: "Desenvolver interface do Builder Shell (com mock data)",
    module: "ui",
    group: "A",
    type: "implementation",
    priority: "high",
    status: "done",
    summary: "Interface base do Builder Shell com Sidebar e Topbar em mock data",
    depends_on: [{ taskId: "DEV-READINESS-BUILDER-SHELL-001", relationship: "depends_on" }],
    blocked_by: [],
    expected_files: ["src/components/builder/shell/BuilderShell.tsx"],
    acceptance_criteria: ["Layout responsivo", "Sem banco real"],
    evidence: [
      { id: "e3", name: "PR-001", filePath: "github.com/pr/1", provided: true }
    ],
    created_at: now,
    updated_at: now,
    source_docs: [],
    next_action: "None",
    is_synthetic: true
  },
  {
    id: "DEV-REVIEW-BUILDER-SHELL-001",
    title: "Revisar implementação do Builder Shell",
    module: "ui",
    group: "A",
    type: "architecture",
    priority: "high",
    status: "done",
    summary: "Relatório de revisão do Builder Shell aprovado",
    depends_on: [{ taskId: "DEV-BUILDER-SHELL-001", relationship: "depends_on" }],
    blocked_by: [],
    expected_files: ["docs/ui/reviews/DEV-REVIEW-BUILDER-SHELL-001_REPORT.md"],
    acceptance_criteria: ["Revisão com sucesso"],
    evidence: [
      { id: "e4", name: "Review Report", filePath: "docs/ui/reviews/DEV-REVIEW-BUILDER-SHELL-001_REPORT.md", provided: true }
    ],
    created_at: now,
    updated_at: now,
    source_docs: [],
    next_action: "None",
    is_synthetic: true
  },
  {
    id: "TASKER-BOARD-001",
    title: "Preparar Tasker Board para desenvolvimento",
    module: "ui",
    group: "A",
    type: "architecture",
    priority: "high",
    status: "done",
    summary: "Contrato e planejamento do Board aprovados",
    depends_on: [],
    blocked_by: [],
    expected_files: ["docs/ui/surfaces/TASKER_BOARD.md"],
    acceptance_criteria: ["Contrato do Tasker Board"],
    evidence: [
      { id: "e5", name: "TASKER_BOARD.md", filePath: "docs/ui/surfaces/TASKER_BOARD.md", provided: true }
    ],
    created_at: now,
    updated_at: now,
    source_docs: [],
    next_action: "None",
    is_synthetic: true
  },
  {
    id: "DEV-READINESS-TASKER-BOARD-001",
    title: "Auditar prontidão para desenvolvimento do Tasker Board",
    module: "tasker",
    group: "A",
    type: "architecture",
    priority: "high",
    status: "done",
    summary: "Contrato auditado e autorizado para dev",
    depends_on: [{ taskId: "TASKER-BOARD-001", relationship: "depends_on" }],
    blocked_by: [],
    expected_files: ["docs/ui/reviews/DEV-READINESS-TASKER-BOARD-001_AUDIT.md"],
    acceptance_criteria: ["Auditoria concluída com limites definidos"],
    evidence: [
      { id: "e6", name: "Audit Report", filePath: "docs/ui/reviews/DEV-READINESS-TASKER-BOARD-001_AUDIT.md", provided: true }
    ],
    created_at: now,
    updated_at: now,
    source_docs: [],
    next_action: "None",
    is_synthetic: true
  },
  {
    id: "DEV-TASKER-BOARD-001",
    title: "Desenvolver interface do Tasker Board (com mock data e limites)",
    module: "ui",
    group: "A",
    type: "implementation",
    priority: "high",
    status: "ready",
    summary: "Implementar UI do Tasker Board, Kanban, cards e transições",
    depends_on: [{ taskId: "DEV-READINESS-TASKER-BOARD-001", relationship: "depends_on" }],
    blocked_by: [],
    expected_files: ["src/components/builder/tasker/TaskerBoard.tsx"],
    acceptance_criteria: ["Kanban renderizado", "Mock data utilizado", "Transições simuladas", "Sem dependência real"],
    evidence: [],
    created_at: now,
    updated_at: now,
    source_docs: ["docs/ui/surfaces/tasker/TASKER_BOARD_MOCK_DATA_CONTRACT.md"],
    next_action: "Implement components",
    is_synthetic: true
  },
  {
    id: "CAPABILITY-EXPLORER-001",
    title: "Preparar Capability Explorer para desenvolvimento",
    module: "ui",
    group: "A",
    type: "architecture",
    priority: "high",
    status: "backlog",
    summary: "Contrato e planejamento do Explorer aprovados",
    depends_on: [],
    blocked_by: [],
    expected_files: [],
    acceptance_criteria: [],
    evidence: [],
    created_at: now,
    updated_at: now,
    source_docs: [],
    next_action: "Plan",
    is_synthetic: true
  },
  {
    id: "PM-INTAKE-001",
    title: "Preparar Process Mirroring Intake",
    module: "ui",
    group: "A",
    type: "architecture",
    priority: "high",
    status: "backlog",
    summary: "Contrato e planejamento do PM Intake aprovados",
    depends_on: [],
    blocked_by: [],
    expected_files: [],
    acceptance_criteria: [],
    evidence: [],
    created_at: now,
    updated_at: now,
    source_docs: [],
    next_action: "Plan",
    is_synthetic: true
  },
  {
    id: "REAL-SRC-002",
    title: "Receber fontes reais anonimizadas",
    module: "process_mirroring",
    group: "D",
    type: "documentation",
    priority: "high",
    status: "blocked",
    summary: "Bloqueado aguardando cliente",
    depends_on: [],
    blocked_by: [{ taskId: "CLIENT_DELIVERY", relationship: "blocked_by" }],
    expected_files: [],
    acceptance_criteria: ["Fontes anonimizadas recebidas"],
    evidence: [],
    created_at: now,
    updated_at: now,
    source_docs: [],
    next_action: "Wait for client",
    is_synthetic: false
  },
  {
    id: "CAP-VAL-002",
    title: "Validar capabilities no piloto real",
    module: "capabilities",
    group: "D",
    type: "contract",
    priority: "high",
    status: "blocked",
    summary: "Bloqueado aguardando piloto",
    depends_on: [{ taskId: "REAL-SRC-002", relationship: "depends_on" }],
    blocked_by: [{ taskId: "REAL-SRC-002", relationship: "blocked_by" }],
    expected_files: [],
    acceptance_criteria: [],
    evidence: [],
    created_at: now,
    updated_at: now,
    source_docs: [],
    next_action: "Wait",
    is_synthetic: false
  },
  {
    id: "GT-PILOT-001",
    title: "Planejar Gestão Técnica como primeiro cliente",
    module: "process_mirroring",
    group: "D",
    type: "architecture",
    priority: "medium",
    status: "blocked",
    summary: "Bloqueado no momento",
    depends_on: [],
    blocked_by: [{ taskId: "PLATFORM_READY", relationship: "blocked_by" }],
    expected_files: [],
    acceptance_criteria: [],
    evidence: [],
    created_at: now,
    updated_at: now,
    source_docs: [],
    next_action: "Wait",
    is_synthetic: false
  },
  {
    id: "GT-RUNTIME-001",
    title: "Desenvolver processo real da Gestão Técnica",
    module: "runtime",
    group: "D",
    type: "implementation",
    priority: "medium",
    status: "blocked",
    summary: "Bloqueado no momento",
    depends_on: [{ taskId: "GT-PILOT-001", relationship: "depends_on" }],
    blocked_by: [{ taskId: "GT-PILOT-001", relationship: "blocked_by" }],
    expected_files: [],
    acceptance_criteria: [],
    evidence: [],
    created_at: now,
    updated_at: now,
    source_docs: [],
    next_action: "Wait",
    is_synthetic: false
  }
];
