import { ViewBlueprint } from "./view-builder-types";

export const VIEW_BLUEPRINTS: ViewBlueprint[] = [
  {
    id: "vb-tech-intake-table-001",
    name: "Technical Service Intake Table View",
    slug: "technical-service-intake-table",
    description: "Visão tabular das entradas de serviço técnico.",
    process_area: "Service",
    view_type: "table",
    data_source_mode: "synthetic",
    readiness_status: "ready_for_demo",
    synthetic: true,
    notes: "Synthetic demo. Not runtime view. Not persisted. No real query. Real sources pending.",
    fields: [
      {
        id: "vf-001",
        label: "Protocol Number",
        key: "protocol_number",
        source_field_key: "protocol",
        field_type: "text",
        visible: true,
        sortable: true,
        filterable: true,
        groupable: false,
        width: "120px",
        format: "bold",
        binding: "form-tech-intake",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: "Mocked sequence"
      },
      {
        id: "vf-002",
        label: "Client Category",
        key: "client_category",
        source_field_key: "category",
        field_type: "enum",
        visible: true,
        sortable: true,
        filterable: true,
        groupable: true,
        width: "150px",
        format: "badge",
        binding: "capability-client",
        data_source_mode: "mock",
        readiness_status: "mock_ready",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-003",
        label: "Status",
        key: "status",
        source_field_key: "state",
        field_type: "enum",
        visible: true,
        sortable: true,
        filterable: true,
        groupable: true,
        width: "100px",
        format: "status_badge",
        binding: "capability-requests",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-004",
        label: "Created At",
        key: "created_at",
        source_field_key: "created_date",
        field_type: "date",
        visible: true,
        sortable: true,
        filterable: true,
        groupable: true,
        width: "140px",
        format: "datetime",
        binding: "capability-audit",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-005",
        label: "Assigned Technician",
        key: "technician",
        source_field_key: "assigned_to",
        field_type: "text",
        visible: false,
        sortable: true,
        filterable: true,
        groupable: true,
        width: "150px",
        format: "text",
        binding: "capability-people",
        data_source_mode: "real_pending",
        readiness_status: "needs_real_sources",
        synthetic: false,
        notes: "Aguardando Gestão Técnica"
      },
      {
        id: "vf-006",
        label: "Priority",
        key: "priority",
        source_field_key: "urgency",
        field_type: "enum",
        visible: true,
        sortable: true,
        filterable: true,
        groupable: true,
        width: "100px",
        format: "badge",
        binding: "form-tech-intake",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-007",
        label: "Machine ID",
        key: "machine_id",
        source_field_key: "equipment_id",
        field_type: "text",
        visible: true,
        sortable: false,
        filterable: true,
        groupable: false,
        width: "120px",
        format: "text",
        binding: "capability-assets",
        data_source_mode: "real_blocked",
        readiness_status: "blocked_runtime",
        synthetic: false,
        notes: "Equipment integration blocked"
      },
      {
        id: "vf-008",
        label: "Reported Issue",
        key: "issue",
        source_field_key: "description",
        field_type: "text",
        visible: false,
        sortable: false,
        filterable: true,
        groupable: false,
        width: "300px",
        format: "truncate",
        binding: "form-tech-intake",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      }
    ],
    columns: [
      { id: "vc-001", field_id: "vf-001", order: 1 },
      { id: "vc-002", field_id: "vf-002", order: 2 },
      { id: "vc-003", field_id: "vf-003", order: 3 },
      { id: "vc-004", field_id: "vf-006", order: 4 },
      { id: "vc-005", field_id: "vf-007", order: 5 },
      { id: "vc-006", field_id: "vf-004", order: 6 },
    ],
    filters: [
      { id: "vfil-001", field_id: "vf-003", filter_type: "status_in" },
      { id: "vfil-002", field_id: "vf-006", filter_type: "equals" },
      { id: "vfil-003", field_id: "vf-004", filter_type: "date_range" },
      { id: "vfil-004", field_id: "vf-002", filter_type: "equals" },
    ],
    sort_rules: [
      { id: "vsr-001", field_id: "vf-004", direction: "desc", order: 1 },
      { id: "vsr-002", field_id: "vf-006", direction: "desc", order: 2 },
    ],
    group_rules: [
      { id: "vgr-001", field_id: "vf-003", order: 1 }
    ],
    actions: [
      { id: "va-001", label: "Open Detail", action_type: "open_detail", icon: "Eye" },
      { id: "va-002", label: "Change Status", action_type: "change_status_placeholder", icon: "Edit" },
      { id: "va-003", label: "Assign", action_type: "assign_placeholder", icon: "User" },
    ],
    layout: {
      show_title: true,
      show_filters: true,
      show_actions: true,
      default_page_size: 20
    },
    bindings: [
      { id: "vbind-001", target_type: "form", target_id: "form-tech-intake", description: "Binds to Intake Form" },
      { id: "vbind-002", target_type: "capability", target_id: "cap-requests", description: "Binds to Requests Capability" },
      { id: "vbind-003", target_type: "capability", target_id: "cap-people", description: "Binds to People Capability" },
      { id: "vbind-004", target_type: "process_step", target_id: "step-initial-triage", description: "Binds to Triage Step" },
    ],
    governance_warnings: [
      { id: "vgw-001", message: "No RBAC filter configured. View may expose all records.", severity: "warning" },
      { id: "vgw-002", message: "Field 'Assigned Technician' requires real pending sources.", severity: "info" },
      { id: "vgw-003", message: "Field 'Machine ID' is blocked by missing runtime capability.", severity: "error" },
    ],
    preview_state: {
      has_mock_data: true,
      mock_row_count: 5
    },
    related_form_blueprints: ["form-tech-intake"],
    related_capabilities: ["cap-requests", "cap-people", "cap-assets"],
    related_process_steps: ["step-initial-triage"],
    related_docs: ["docs/ui/surfaces/VIEW_BUILDER.md"]
  },
  {
    id: "vb-tech-intake-kanban-001",
    name: "Technical Service Kanban View",
    slug: "technical-service-intake-kanban",
    description: "Visão Kanban das entradas de serviço técnico.",
    process_area: "Service",
    view_type: "kanban",
    data_source_mode: "synthetic",
    readiness_status: "ready_for_demo",
    synthetic: true,
    notes: "Synthetic demo. Kanban layout.",
    fields: [
      {
        id: "vf-k-001",
        label: "Title",
        key: "title",
        source_field_key: "protocol",
        field_type: "text",
        visible: true,
        sortable: false,
        filterable: true,
        groupable: false,
        width: "auto",
        format: "bold",
        binding: "form-tech-intake",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-k-002",
        label: "Status",
        key: "status",
        source_field_key: "state",
        field_type: "enum",
        visible: true,
        sortable: false,
        filterable: true,
        groupable: true,
        width: "auto",
        format: "board_column",
        binding: "capability-requests",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: "Column driver"
      },
      {
        id: "vf-k-003",
        label: "Assignee",
        key: "assignee",
        source_field_key: "assigned_to",
        field_type: "text",
        visible: true,
        sortable: false,
        filterable: true,
        groupable: false,
        width: "auto",
        format: "avatar",
        binding: "capability-people",
        data_source_mode: "real_pending",
        readiness_status: "needs_real_sources",
        synthetic: false,
        notes: ""
      },
      {
        id: "vf-k-004",
        label: "Priority",
        key: "priority",
        source_field_key: "urgency",
        field_type: "enum",
        visible: true,
        sortable: true,
        filterable: true,
        groupable: false,
        width: "auto",
        format: "badge",
        binding: "form-tech-intake",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-k-005",
        label: "Client",
        key: "client",
        source_field_key: "client_name",
        field_type: "text",
        visible: true,
        sortable: true,
        filterable: true,
        groupable: true,
        width: "auto",
        format: "text",
        binding: "capability-client",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-k-006",
        label: "Due Date",
        key: "due_date",
        source_field_key: "deadline",
        field_type: "date",
        visible: false,
        sortable: true,
        filterable: true,
        groupable: false,
        width: "auto",
        format: "date",
        binding: "form-tech-intake",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-k-007",
        label: "Machine ID",
        key: "machine_id",
        source_field_key: "equipment_id",
        field_type: "text",
        visible: false,
        sortable: false,
        filterable: false,
        groupable: false,
        width: "auto",
        format: "text",
        binding: "capability-assets",
        data_source_mode: "real_blocked",
        readiness_status: "blocked_runtime",
        synthetic: false,
        notes: ""
      },
      {
        id: "vf-k-008",
        label: "Reported Issue",
        key: "issue",
        source_field_key: "description",
        field_type: "text",
        visible: false,
        sortable: false,
        filterable: false,
        groupable: false,
        width: "auto",
        format: "text",
        binding: "form-tech-intake",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      }
    ],
    columns: [],
    filters: [
      { id: "vfil-k-001", field_id: "vf-k-003", filter_type: "equals" },
      { id: "vfil-k-002", field_id: "vf-k-004", filter_type: "equals" },
      { id: "vfil-k-003", field_id: "vf-k-005", filter_type: "text_contains" },
      { id: "vfil-k-004", field_id: "vf-k-002", filter_type: "not_equals" },
    ],
    sort_rules: [
      { id: "vsr-k-001", field_id: "vf-k-004", direction: "desc", order: 1 },
      { id: "vsr-k-002", field_id: "vf-k-006", direction: "asc", order: 2 }
    ],
    group_rules: [
      { id: "vgr-k-001", field_id: "vf-k-002", order: 1 }
    ],
    actions: [
      { id: "va-k-001", label: "Open Card", action_type: "open_detail" },
      { id: "va-k-002", label: "Move Status", action_type: "change_status_placeholder" },
      { id: "va-k-003", label: "Quick Assign", action_type: "assign_placeholder" }
    ],
    layout: {
      show_title: true,
      show_filters: true,
      show_actions: false,
      default_page_size: 50
    },
    bindings: [
      { id: "vbind-k-001", target_type: "form", target_id: "form-tech-intake", description: "Binds to Intake Form" },
      { id: "vbind-k-002", target_type: "capability", target_id: "cap-requests", description: "Binds to Requests Capability" },
      { id: "vbind-k-003", target_type: "capability", target_id: "cap-people", description: "Binds to People Capability" },
      { id: "vbind-k-004", target_type: "process_step", target_id: "step-execution", description: "Binds to Execution Step" }
    ],
    governance_warnings: [
      { id: "vgw-k-001", message: "Kanban views without RBAC can lead to visual clutter and data leaks.", severity: "warning" },
      { id: "vgw-k-002", message: "Real Assignee data is pending.", severity: "info" },
      { id: "vgw-k-003", message: "Asset Capability is blocked, Machine ID cannot be resolved.", severity: "error" },
    ],
    preview_state: {
      has_mock_data: true,
      mock_row_count: 12
    },
    related_form_blueprints: ["form-tech-intake"],
    related_capabilities: ["cap-requests", "cap-people"],
    related_process_steps: ["step-execution"],
    related_docs: [],
  },
  {
    id: "vb-clinic-calendar-001",
    name: "Clinic Appointment Calendar View",
    slug: "clinic-appointment-calendar",
    description: "Visão calendário de agendamentos.",
    process_area: "Scheduling",
    view_type: "calendar",
    data_source_mode: "synthetic",
    readiness_status: "ready_for_demo",
    synthetic: true,
    notes: "Synthetic demo.",
    fields: [
      {
        id: "vf-cal-001",
        label: "Title",
        key: "title",
        source_field_key: "patient_name",
        field_type: "text",
        visible: true,
        sortable: false,
        filterable: true,
        groupable: false,
        width: "auto",
        format: "text",
        binding: "form-appointment",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-cal-002",
        label: "Start Time",
        key: "start_time",
        source_field_key: "appointment_start",
        field_type: "date",
        visible: true,
        sortable: true,
        filterable: true,
        groupable: false,
        width: "auto",
        format: "datetime",
        binding: "form-appointment",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: "Event Start"
      },
      {
        id: "vf-cal-003",
        label: "End Time",
        key: "end_time",
        source_field_key: "appointment_end",
        field_type: "date",
        visible: true,
        sortable: true,
        filterable: true,
        groupable: false,
        width: "auto",
        format: "datetime",
        binding: "form-appointment",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: "Event End"
      },
      {
        id: "vf-cal-004",
        label: "Doctor",
        key: "doctor",
        source_field_key: "provider",
        field_type: "text",
        visible: true,
        sortable: true,
        filterable: true,
        groupable: true,
        width: "auto",
        format: "text",
        binding: "capability-people",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-cal-005",
        label: "Status",
        key: "status",
        source_field_key: "state",
        field_type: "enum",
        visible: true,
        sortable: false,
        filterable: true,
        groupable: true,
        width: "auto",
        format: "badge",
        binding: "capability-scheduling",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-cal-006",
        label: "Room",
        key: "room",
        source_field_key: "location",
        field_type: "text",
        visible: false,
        sortable: true,
        filterable: true,
        groupable: true,
        width: "auto",
        format: "text",
        binding: "capability-assets",
        data_source_mode: "real_blocked",
        readiness_status: "blocked_runtime",
        synthetic: false,
        notes: ""
      },
      {
        id: "vf-cal-007",
        label: "Insurance",
        key: "insurance",
        source_field_key: "plan",
        field_type: "text",
        visible: false,
        sortable: false,
        filterable: true,
        groupable: false,
        width: "auto",
        format: "text",
        binding: "form-appointment",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-cal-008",
        label: "Patient ID",
        key: "patient_id",
        source_field_key: "record_id",
        field_type: "text",
        visible: false,
        sortable: false,
        filterable: false,
        groupable: false,
        width: "auto",
        format: "hidden",
        binding: "capability-client",
        data_source_mode: "real_pending",
        readiness_status: "needs_real_sources",
        synthetic: false,
        notes: ""
      }
    ],
    columns: [],
    filters: [
      { id: "vfil-cal-001", field_id: "vf-cal-004", filter_type: "equals" },
      { id: "vfil-cal-002", field_id: "vf-cal-005", filter_type: "status_in" },
      { id: "vfil-cal-003", field_id: "vf-cal-006", filter_type: "equals" },
      { id: "vfil-cal-004", field_id: "vf-cal-002", filter_type: "date_range" }
    ],
    sort_rules: [
      { id: "vsr-cal-001", field_id: "vf-cal-002", direction: "asc", order: 1 },
      { id: "vsr-cal-002", field_id: "vf-cal-004", direction: "asc", order: 2 }
    ],
    group_rules: [
      { id: "vgr-cal-001", field_id: "vf-cal-004", order: 1 }
    ],
    actions: [
      { id: "va-cal-001", label: "View Details", action_type: "open_detail" },
      { id: "va-cal-002", label: "Reschedule", action_type: "future_runtime_action" },
      { id: "va-cal-003", label: "Cancel", action_type: "change_status_placeholder" }
    ],
    layout: {
      show_title: true,
      show_filters: true,
      show_actions: true,
      default_page_size: 30
    },
    bindings: [
      { id: "vbind-cal-001", target_type: "form", target_id: "form-appointment", description: "Binds to Appointment Form" },
      { id: "vbind-cal-002", target_type: "capability", target_id: "cap-scheduling", description: "Binds to Scheduling Capability" },
      { id: "vbind-cal-003", target_type: "capability", target_id: "cap-people", description: "Binds to People Capability" },
      { id: "vbind-cal-004", target_type: "process_step", target_id: "step-booking", description: "Binds to Booking Step" }
    ],
    governance_warnings: [
      { id: "vgw-cal-001", message: "Calendar views should default to the current user's scope.", severity: "warning" },
      { id: "vgw-cal-002", message: "Patient ID is pending real sources, anonymization rules apply.", severity: "info" },
      { id: "vgw-cal-003", message: "Room allocation is blocked until Assets capability is ready.", severity: "error" }
    ],
    preview_state: {
      has_mock_data: true,
      mock_row_count: 8
    },
    related_form_blueprints: ["form-appointment"],
    related_capabilities: ["cap-scheduling", "cap-people"],
    related_process_steps: ["step-booking"],
    related_docs: []
  },
  {
    id: "vb-repair-master-001",
    name: "Workshop Repair Master Detail View",
    slug: "workshop-repair-master-detail",
    description: "Visão Master-Detail para ordens de reparo.",
    process_area: "Service",
    view_type: "split_master_detail",
    data_source_mode: "synthetic",
    readiness_status: "ready_for_demo",
    synthetic: true,
    notes: "Synthetic demo.",
    fields: [
      {
        id: "vf-md-001",
        label: "Order ID",
        key: "order_id",
        source_field_key: "work_order_id",
        field_type: "text",
        visible: true,
        sortable: true,
        filterable: true,
        groupable: false,
        width: "100px",
        format: "bold",
        binding: "capability-work_orders",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-md-002",
        label: "Status",
        key: "status",
        source_field_key: "state",
        field_type: "enum",
        visible: true,
        sortable: true,
        filterable: true,
        groupable: true,
        width: "120px",
        format: "badge",
        binding: "capability-work_orders",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-md-003",
        label: "Technician",
        key: "technician",
        source_field_key: "assigned_tech",
        field_type: "text",
        visible: true,
        sortable: true,
        filterable: true,
        groupable: true,
        width: "150px",
        format: "text",
        binding: "capability-people",
        data_source_mode: "real_pending",
        readiness_status: "needs_real_sources",
        synthetic: false,
        notes: ""
      },
      {
        id: "vf-md-004",
        label: "Estimated Cost",
        key: "est_cost",
        source_field_key: "budget",
        field_type: "number",
        visible: false,
        sortable: true,
        filterable: false,
        groupable: false,
        width: "100px",
        format: "currency",
        binding: "form-repair",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-md-005",
        label: "Actual Cost",
        key: "act_cost",
        source_field_key: "final_cost",
        field_type: "number",
        visible: false,
        sortable: true,
        filterable: false,
        groupable: false,
        width: "100px",
        format: "currency",
        binding: "form-repair",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-md-006",
        label: "Parts Required",
        key: "parts",
        source_field_key: "bom",
        field_type: "text",
        visible: false,
        sortable: false,
        filterable: true,
        groupable: false,
        width: "200px",
        format: "text",
        binding: "capability-inventory",
        data_source_mode: "real_blocked",
        readiness_status: "blocked_runtime",
        synthetic: false,
        notes: ""
      },
      {
        id: "vf-md-007",
        label: "Start Date",
        key: "start_date",
        source_field_key: "started_at",
        field_type: "date",
        visible: true,
        sortable: true,
        filterable: true,
        groupable: false,
        width: "120px",
        format: "date",
        binding: "capability-work_orders",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      },
      {
        id: "vf-md-008",
        label: "Notes",
        key: "notes",
        source_field_key: "tech_notes",
        field_type: "text",
        visible: false,
        sortable: false,
        filterable: false,
        groupable: false,
        width: "auto",
        format: "text",
        binding: "form-repair",
        data_source_mode: "synthetic",
        readiness_status: "ready_for_demo",
        synthetic: true,
        notes: ""
      }
    ],
    columns: [
      { id: "vc-md-001", field_id: "vf-md-001", order: 1 },
      { id: "vc-md-002", field_id: "vf-md-002", order: 2 },
      { id: "vc-md-003", field_id: "vf-md-007", order: 3 },
      { id: "vc-md-004", field_id: "vf-md-003", order: 4 }
    ],
    filters: [
      { id: "vfil-md-001", field_id: "vf-md-002", filter_type: "status_in" },
      { id: "vfil-md-002", field_id: "vf-md-003", filter_type: "equals" },
      { id: "vfil-md-003", field_id: "vf-md-007", filter_type: "date_range" },
      { id: "vfil-md-004", field_id: "vf-md-006", filter_type: "text_contains" }
    ],
    sort_rules: [
      { id: "vsr-md-001", field_id: "vf-md-007", direction: "desc", order: 1 },
      { id: "vsr-md-002", field_id: "vf-md-001", direction: "desc", order: 2 }
    ],
    group_rules: [
      { id: "vgr-md-001", field_id: "vf-md-002", order: 1 }
    ],
    actions: [
      { id: "va-md-001", label: "Add Note", action_type: "create_related_placeholder", icon: "Plus" },
      { id: "va-md-002", label: "Complete Order", action_type: "change_status_placeholder", icon: "Check" },
      { id: "va-md-003", label: "Print Tag", action_type: "export_placeholder", icon: "Printer" }
    ],
    layout: {
      show_title: true,
      show_filters: true,
      show_actions: true,
      default_page_size: 15
    },
    bindings: [
      { id: "vbind-md-001", target_type: "form", target_id: "form-repair", description: "Binds to Repair Form" },
      { id: "vbind-md-002", target_type: "capability", target_id: "cap-work_orders", description: "Binds to Work Orders Capability" },
      { id: "vbind-md-003", target_type: "capability", target_id: "cap-people", description: "Binds to People Capability" },
      { id: "vbind-md-004", target_type: "process_step", target_id: "step-repair", description: "Binds to Repair Step" }
    ],
    governance_warnings: [
      { id: "vgw-md-001", message: "Financial fields are hidden by default, ensure RBAC is applied if toggled.", severity: "warning" },
      { id: "vgw-md-002", message: "Technician data is synthetic.", severity: "info" },
      { id: "vgw-md-003", message: "Inventory capability is missing.", severity: "error" }
    ],
    preview_state: {
      has_mock_data: true,
      mock_row_count: 6
    },
    related_form_blueprints: ["form-repair"],
    related_capabilities: ["cap-work_orders", "cap-people"],
    related_process_steps: ["step-repair"],
    related_docs: []
  }
];
