export const systemBuilderAdaptation = {
  key: "system-builder",
  name: "System Builder Baseline",
  workspaceName: "System Builder Dev",
  terminology: {
    workItem: "Demanda",
    workItems: "Demandas",
    serviceOrder: "Execucao",
    serviceOrders: "Execucoes",
    asset: "Entidade",
    assets: "Entidades",
    technician: "Responsavel",
    technicians: "Responsaveis",
    workforce: "Responsaveis",
    shift: "Janela Operacional",
    shifts: "Janelas Operacionais",
    shiftLog: "Registro de Continuidade",
    shiftLogs: "Registros de Continuidade",
    supervisor: "Aprovador",
    technicalSecretary: "Preparador Documental",
    legacySystem: "Sistema Externo",
  },
  demandTypes: [
    {
      key: "solicitacao",
      label: "Necessidade",
      description: "Entrada operacional ainda em compreensao.",
      defaultPriority: "medium",
      canGenerateServiceOrder: true,
      canAppearInShiftLog: true,
      defaultQueue: "compreensao",
    },
    {
      key: "incidente",
      label: "Incidente",
      description: "Interrupcao, falha ou degradacao de uma capacidade.",
      defaultPriority: "high",
      canGenerateServiceOrder: true,
      canAppearInShiftLog: true,
      defaultQueue: "triagem",
    },
    {
      key: "atividade_planejada",
      label: "Melhoria",
      description: "Oportunidade de evolucao depois que o processo foi espelhado.",
      defaultPriority: "medium",
      canGenerateServiceOrder: true,
      canAppearInShiftLog: false,
      defaultQueue: "evolucao",
    },
  ],
  serviceOrderTypes: [
    {
      key: "manutencao",
      label: "Execucao Operacional",
      description: "Acao autorizada para produzir um resultado rastreavel.",
      requiresAsset: false,
      requiresTimeEntry: true,
      requiresEvidence: true,
      requiresSupervisorApproval: true,
    },
    {
      key: "vistoria",
      label: "Analise Processual",
      description: "Trabalho de compreensao, espelhamento ou estabilizacao de processo.",
      requiresAsset: false,
      requiresTimeEntry: true,
      requiresEvidence: false,
      requiresSupervisorApproval: false,
    },
  ],
  assetTypes: [
    {
      key: "operational_entity",
      label: "Entidade Operacional",
      tracksMaintenance: false,
      tracksLocation: false,
    },
    {
      key: "resource",
      label: "Recurso",
      tracksMaintenance: true,
      tracksLocation: true,
    },
    {
      key: "digital_service",
      label: "Servico Digital",
      tracksMaintenance: true,
      tracksLocation: false,
    },
  ],
  shiftTypes: [
    {
      key: "expediente",
      label: "Janela Operacional",
      description: "Periodo em que uma capacidade esta disponivel para execucao.",
      requiresShiftLog: false,
      receivesTickets: true,
      receivesServiceOrders: true,
      allowsOverlap: true,
    },
    {
      key: "plantao",
      label: "Continuidade",
      description: "Janela que exige registro formal de passagem ou acompanhamento.",
      requiresShiftLog: true,
      receivesTickets: true,
      receivesServiceOrders: true,
      allowsOverlap: false,
    },
  ],
  businessRoles: [
    {
      key: "process_owner",
      legacyLevel: "supervisor",
      label: "Dono do Processo",
      canExecuteServiceOrder: true,
      canAssignServiceOrder: true,
      canApprove: true,
      canReviewShiftLog: true,
      canValidateTechnicalWork: true,
    },
    {
      key: "operator",
      legacyLevel: "pleno",
      label: "Executor Operacional",
      canExecuteServiceOrder: true,
      requiresSupervision: false,
      canApprove: false,
      canAssignServiceOrder: false,
    },
    {
      key: "document_controller",
      label: "Controlador Documental",
      canPrepareDocuments: true,
      canReviewCompleteness: true,
      canApprove: false,
      canExecuteServiceOrder: false,
    },
  ],
  workflows: [
    {
      key: "work_item_default",
      label: "Fluxo Padrao de Demanda",
      target: "work_item",
      states: ["draft", "open", "triaged", "planned", "in_progress", "blocked", "resolved", "cancelled"],
    },
    {
      key: "service_order_default",
      label: "Fluxo Padrao de Execucao",
      target: "service_order",
      states: ["draft", "open", "assigned", "in_progress", "waiting_review", "completed", "approved", "cancelled"],
    },
    {
      key: "document_default",
      label: "Fluxo Padrao de Documento",
      target: "technical_document",
      states: ["draft", "waiting_technician_review", "waiting_supervisor_approval", "approved", "archived", "returned_for_correction"],
    },
  ],
  queues: [
    {
      key: "compreensao",
      label: "Compreensao",
      description: "Fila para entender a operacao antes de automatizar.",
    },
    {
      key: "triagem",
      label: "Triagem",
      description: "Fila de classificacao e encaminhamento inicial.",
    },
    {
      key: "evolucao",
      label: "Evolucao",
      description: "Fila de melhorias sobre processos ja espelhados.",
    },
  ],
  reportTemplates: [
    {
      key: "process_instance_summary",
      label: "Resumo de Instancia de Processo",
      target: "process_instance",
    },
    {
      key: "operational_timeline",
      label: "Linha do Tempo Operacional",
      target: "event_stream",
    },
  ],
  documentTemplates: [
    {
      key: "operational_protocol",
      label: "Protocolo Operacional",
      target: "process_definition",
    },
    {
      key: "execution_receipt",
      label: "Canhoto de Execucao",
      target: "service_order",
    },
  ],
  legacyConfig: {
    enabled: false,
    systemName: "Sistema Externo",
    mode: "manual-first",
    storesProtocolNumber: true,
    storesExternalRecordId: true,
    storesExternalStatus: true,
    futureAutomation: {
      enabled: false,
      strategy: "integration-action",
    },
  },
} as const;

export type SystemBuilderAdaptation = typeof systemBuilderAdaptation;
