import test from "node:test";
import assert from "node:assert";
import proxyquire from "proxyquire";

const { POST } = proxyquire("@/app/api/agent/route", {
  "@/features/platform/gateway/agent-gateway.service": {
    submitCandidateFromAgent: async (payload: any) => {
      return {
        id: "mock-id-123",
        ...payload,
        status: "draft",
        origin: "agent",
        createdAt: new Date(),
        updatedAt: new Date(),
      };
    },
  },
});

test("Agent Gateway API Route Validation", async (t) => {
  const originalEnv = process.env.AGENT_GATEWAY_KEY;
  process.env.AGENT_GATEWAY_KEY = "test-secret-key";

  t.after(() => {
    process.env.AGENT_GATEWAY_KEY = originalEnv;
  });

  await t.test("Returns 401 if x-agent-key is missing", async () => {
    const request = new Request("http://localhost/api/agent", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({}),
    });
    const response = await POST(request);
    assert.strictEqual(response.status, 401);
  });

  await t.test("Returns 401 if x-agent-key is invalid", async () => {
    const request = new Request("http://localhost/api/agent", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-agent-key": "wrong-key",
      },
      body: JSON.stringify({}),
    });
    const response = await POST(request);
    assert.strictEqual(response.status, 401);
  });

  await t.test("Returns 400 for invalid payload", async () => {
    const request = new Request("http://localhost/api/agent", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-agent-key": "test-secret-key",
      },
      body: JSON.stringify({ name: "Test Candidate" }),
    });
    const response = await POST(request);
    assert.strictEqual(response.status, 400);
  });

  await t.test("Returns 200 with valid payload and key", async () => {
    const workspaceId = "00000000-0000-0000-0000-000000000000";
    const request = new Request("http://localhost/api/agent", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-agent-key": "test-secret-key",
      },
      body: JSON.stringify({
        workspaceId,
        name: "Test Candidate via Agent",
        description: "Generated by agent",
        proposedDefinition: { nodes: [], edges: [] }
      }),
    });

    const response = await POST(request);
    assert.strictEqual(response.status, 200);

    const json = await response.json();
    assert.strictEqual(json.ok, true);
    assert.strictEqual(json.data.workspaceId, workspaceId);
    assert.strictEqual(json.data.name, "Test Candidate via Agent");
    assert.strictEqual(json.data.origin, "agent");
    assert.strictEqual(json.data.status, "draft");
  });
});
