import { getAgentWorkDb } from "../db";
import { agentWorkers, agentExecutionWaves, agentWorkPackages, agentPackageTasks } from "../schema";

export async function seedWave01(baseSha: string) {
  const db = getAgentWorkDb();
  if (!baseSha || baseSha.length < 40) {
     throw new Error("A valid real base SHA must be provided");
  }

  await db.insert(agentWorkers).values([
    { key: "jules-coordinator-01", name: "Coordinator", role: "coordinator", status: "active" },
    { key: "jules-reviewer-module-01", name: "Reviewer Module", role: "reviewer", status: "active" },
    { key: "jules-integrator-01", name: "Integrator", role: "integrator", status: "active" },
    { key: "jules-documentator-01", name: "Documentator", role: "documentator", status: "active" },
    { key: "jules-dev-shared-contracts-01", name: "Dev Shared Contracts", role: "module_worker", status: "active" },
    { key: "jules-dev-runtime-types-01", name: "Dev Runtime Types", role: "module_worker", status: "active" },
    { key: "jules-dev-runtime-tenancy-01", name: "Dev Runtime Tenancy", role: "module_worker", status: "active" },
    { key: "jules-dev-events-01", name: "Dev Events", role: "module_worker", status: "active" }
  ]).onConflictDoNothing();

  await db.insert(agentExecutionWaves).values([
    { key: "WAVE-01-FOUNDATION", title: "Foundation Wave", status: "planned", objective: "Foundation", baseBranch: "main", baseSha: baseSha, integrationBranch: "integration/wave-01" },
  ]).onConflictDoNothing();

  const packages = [
    {
      key: "PKG-SHARED-CONTRACTS-001",
      title: "Shared Contracts",
      moduleKey: "shared-contracts",
      laneKey: "lane1",
      workerRole: "module_worker",
      waveKey: "WAVE-01-FOUNDATION",
      packageSize: "M",
      priority: 1,
      status: "ready",
      objective: "Define basic type schemas",
      expectedOutcome: "Zod schemas for base concepts",
      baseBranch: "main",
      baseSha: baseSha,
      targetBranch: "feat/shared-contracts",
      integrationBranch: "integration/wave-01",
      ownedPaths: ["src/platform/contracts/**"],
      readOnlyPaths: [],
      forbiddenPaths: [],
      readFirst: [],
      requiredTests: ["test1", "test2"],
      acceptanceCriteria: ["ac1"],
      documentationImpacts: [],
      integrationRisk: "low",
      mergeOrder: 1,
      contractsConsumed: [],
      contractsProduced: ["base-schema"],
      publicContractsChanged: [],
      knownConsumers: [],
      schemaImpacts: [],
      reviewBudget: {},
      createdBy: "seed"
    },
    {
      key: "PKG-RUNTIME-TYPES-MAPPERS-001",
      title: "Runtime Types",
      moduleKey: "runtime-engine",
      laneKey: "lane2",
      workerRole: "module_worker",
      waveKey: "WAVE-01-FOUNDATION",
      packageSize: "M",
      priority: 2,
      status: "ready",
      objective: "Define runtime type maps",
      expectedOutcome: "Mappers for runtime execution",
      baseBranch: "main",
      baseSha: baseSha,
      targetBranch: "feat/runtime-types",
      integrationBranch: "integration/wave-01",
      ownedPaths: ["src/adaptations/runtime/**"],
      readOnlyPaths: ["src/platform/contracts/**"],
      forbiddenPaths: [],
      readFirst: [],
      requiredTests: ["test1", "test2"],
      acceptanceCriteria: ["ac1"],
      documentationImpacts: [],
      integrationRisk: "medium",
      mergeOrder: 2,
      contractsConsumed: ["base-schema"],
      contractsProduced: [],
      publicContractsChanged: [],
      knownConsumers: [],
      schemaImpacts: [],
      reviewBudget: {},
      createdBy: "seed"
    },
    {
      key: "PKG-RUNTIME-TENANCY-001",
      title: "Runtime Tenancy",
      moduleKey: "runtime-engine",
      laneKey: "lane2",
      workerRole: "module_worker",
      waveKey: "WAVE-01-FOUNDATION",
      packageSize: "M",
      priority: 3,
      status: "ready",
      objective: "Define runtime tenancy maps",
      expectedOutcome: "Mappers for runtime tenancy",
      baseBranch: "main",
      baseSha: baseSha,
      targetBranch: "feat/runtime-tenancy",
      integrationBranch: "integration/wave-01",
      ownedPaths: ["src/adaptations/runtime/tenancy/**"],
      readOnlyPaths: ["src/platform/contracts/**"],
      forbiddenPaths: [],
      readFirst: [],
      requiredTests: ["test1", "test2"],
      acceptanceCriteria: ["ac1"],
      documentationImpacts: [],
      integrationRisk: "medium",
      mergeOrder: 3,
      contractsConsumed: ["base-schema"],
      contractsProduced: [],
      publicContractsChanged: [],
      knownConsumers: [],
      schemaImpacts: [],
      reviewBudget: {},
      createdBy: "seed"
    },
    {
      key: "PKG-EVENT-TYPES-MAPPERS-001",
      title: "Event Types",
      moduleKey: "events-receipts",
      laneKey: "lane3",
      workerRole: "module_worker",
      waveKey: "WAVE-01-FOUNDATION",
      packageSize: "M",
      priority: 4,
      status: "ready",
      objective: "Define event type maps",
      expectedOutcome: "Mappers for events",
      baseBranch: "main",
      baseSha: baseSha,
      targetBranch: "feat/event-types",
      integrationBranch: "integration/wave-01",
      ownedPaths: ["src/adaptations/events/**"],
      readOnlyPaths: ["src/platform/contracts/**"],
      forbiddenPaths: [],
      readFirst: [],
      requiredTests: ["test1", "test2"],
      acceptanceCriteria: ["ac1"],
      documentationImpacts: [],
      integrationRisk: "medium",
      mergeOrder: 4,
      contractsConsumed: ["base-schema"],
      contractsProduced: [],
      publicContractsChanged: [],
      knownConsumers: [],
      schemaImpacts: [],
      reviewBudget: {},
      createdBy: "seed"
    },
    {
      key: "PKG-OPERATION-DOCS-FOUNDATION-001",
      title: "Ops Docs Foundation",
      moduleKey: "documentation-governance",
      laneKey: "lane4",
      workerRole: "documentator",
      waveKey: "WAVE-01-FOUNDATION",
      packageSize: "M",
      priority: 5,
      status: "ready",
      objective: "Define ops docs",
      expectedOutcome: "Ops docs updated",
      baseBranch: "main",
      baseSha: baseSha,
      targetBranch: "feat/ops-docs",
      integrationBranch: "integration/wave-01",
      ownedPaths: ["docs/operations/**"],
      readOnlyPaths: [],
      forbiddenPaths: [],
      readFirst: [],
      requiredTests: ["test1", "test2"],
      acceptanceCriteria: ["ac1"],
      documentationImpacts: [],
      integrationRisk: "low",
      mergeOrder: 5,
      contractsConsumed: [],
      contractsProduced: [],
      publicContractsChanged: [],
      knownConsumers: [],
      schemaImpacts: [],
      reviewBudget: {},
      createdBy: "seed"
    }
  ];

  for (const pkg of packages) {
      await db.insert(agentWorkPackages).values(pkg as any).onConflictDoNothing();

      const tasks = [
          { id: crypto.randomUUID(), key: crypto.randomUUID(), packageKey: pkg.key, title: "Task A Setup", description: "Setup the foundation", order: 1, status: "pending", taskType: "implementation", acceptanceCriteria: [], expectedArtifacts: [] },
          { id: crypto.randomUUID(), key: crypto.randomUUID(), packageKey: pkg.key, title: "Task B Core", description: "Implement core logic", order: 2, status: "pending", taskType: "implementation", acceptanceCriteria: [], expectedArtifacts: [] },
          { id: crypto.randomUUID(), key: crypto.randomUUID(), packageKey: pkg.key, title: "Task C Tests", description: "Write tests", order: 3, status: "pending", taskType: "test", acceptanceCriteria: [], expectedArtifacts: [] },
      ];
      await db.insert(agentPackageTasks).values(tasks).onConflictDoNothing();
  }
}
