import { DocsItem } from "./docs-types";

export const STATIC_DOCS_INDEX: DocsItem[] = [
  {
    id: "doc-1",
    title: "Project Manifest",
    slug: "project-manifest",
    category: "manifest",
    module: "core",
    phase: "approved",
    status: "done",
    summary: "O manifesto original detalhando o propósito central, escopo primário e prioridades de negócio do System Builder.",
    source_path: "docs/PROJECT_MANIFEST.md",
    related_docs: [{ id: "doc-2", type: "doc", label: "Architecture" }],
    related_tasks: [],
    related_capabilities: ["platform_core"],
    tags: ["foundation", "vision"],
    last_known_state: "Approved v1.0",
    synthetic: false,
  },
  {
    id: "doc-2",
    title: "System Architecture",
    slug: "architecture",
    category: "architecture",
    module: "core",
    phase: "approved",
    status: "done",
    summary: "Estrutura fundamental do System Builder: Domain Driven Design, divisão Builder/Runtime.",
    source_path: "docs/ARCHITECTURE.md",
    related_docs: [{ id: "doc-5", type: "doc", label: "DEC-SB-001" }],
    related_tasks: [],
    related_capabilities: ["platform_core"],
    tags: ["architecture", "ddd", "layers"],
    last_known_state: "Active",
    synthetic: false,
  },
  {
    id: "doc-3",
    title: "Development Rules",
    slug: "development-rules",
    category: "governance",
    module: "core",
    phase: "approved",
    status: "done",
    summary: "Regras rígidas de desenvolvimento: Frontend parity gate, agents limits e stop rules.",
    source_path: "docs/DEVELOPMENT_RULES.md",
    related_docs: [{ id: "doc-1", type: "doc", label: "Manifest" }],
    related_tasks: [],
    related_capabilities: ["platform_core"],
    tags: ["rules", "gate"],
    last_known_state: "Enforced",
    synthetic: false,
  },
  {
    id: "doc-4",
    title: "Agent Boundaries",
    slug: "agents",
    category: "governance",
    module: "core",
    phase: "approved",
    status: "done",
    summary: "Limitações e boundaries dos agentes atuando no repositório.",
    source_path: "AGENTS.md",
    related_docs: [],
    related_tasks: [],
    related_capabilities: ["platform_core"],
    tags: ["agents", "rules"],
    last_known_state: "Enforced",
    synthetic: false,
  },
  {
    id: "doc-5",
    title: "DEC-SB-001: Platform First",
    slug: "dec-sb-001",
    category: "decision",
    module: "core",
    phase: "approved",
    status: "done",
    summary: "Decisão arquitetural formalizando a prioridade no System Builder Base.",
    source_path: "docs/decisions/DEC-SB-001.md",
    related_docs: [{ id: "doc-2", type: "doc", label: "Architecture" }],
    related_tasks: [],
    related_capabilities: ["platform_core"],
    tags: ["adr", "platform"],
    last_known_state: "Approved",
    synthetic: false,
  },
  {
    id: "doc-6",
    title: "Sprint Board",
    slug: "sprint-board",
    category: "tasker",
    module: "tasker",
    phase: "development",
    status: "ready",
    summary: "Quadro de tarefas focado na entrega incremental via sprints orientados a plataforma.",
    source_path: "docs/tasker/SPRINT_BOARD.md",
    related_docs: [{ id: "doc-7", type: "doc", label: "Backlog" }],
    related_tasks: [],
    related_capabilities: ["platform_core"],
    tags: ["sprint", "management"],
    last_known_state: "Active Sprint",
    synthetic: true,
  },
  {
    id: "doc-7",
    title: "Backlog Master",
    slug: "backlog",
    category: "tasker",
    module: "tasker",
    phase: "planning",
    status: "ready",
    summary: "O backlog completo contendo as próximas tarefas listadas pela arquitetura do Builder.",
    source_path: "docs/tasker/BACKLOG.md",
    related_docs: [],
    related_tasks: [],
    related_capabilities: ["platform_core"],
    tags: ["backlog", "planning"],
    last_known_state: "Active",
    synthetic: true,
  },
  {
    id: "doc-8",
    title: "Dev Readiness Matrix",
    slug: "dev-readiness-matrix",
    category: "readiness",
    module: "tasker",
    phase: "readiness",
    status: "ready",
    summary: "Matriz que avalia dependências antes que o código de UIs seja implementado.",
    source_path: "docs/tasker/DEV_READINESS_MATRIX.md",
    related_docs: [],
    related_tasks: [],
    related_capabilities: ["platform_core"],
    tags: ["gate", "readiness"],
    last_known_state: "Enforced",
    synthetic: true,
  },
  {
    id: "doc-9",
    title: "View Contract Master",
    slug: "view-contract",
    category: "ui_contract",
    module: "core",
    phase: "approved",
    status: "done",
    summary: "Contrato central de UIs mapeando as superfícies prioritárias do Grupo A.",
    source_path: "docs/ui/VIEW_CONTRACT.md",
    related_docs: [{ id: "doc-10", type: "doc", label: "Builder Shell UI" }],
    related_tasks: [],
    related_capabilities: ["platform_core"],
    tags: ["ui", "contract"],
    last_known_state: "Active",
    synthetic: false,
  },
  {
    id: "doc-10",
    title: "Builder Shell UI",
    slug: "builder-shell-ui",
    category: "ui_contract",
    module: "shell",
    phase: "approved",
    status: "done",
    summary: "Contrato da UI do Builder Shell.",
    source_path: "docs/ui/surfaces/BUILDER_SHELL.md",
    related_docs: [],
    related_tasks: [{ id: "task-1", type: "task", label: "DEV-BUILDER-SHELL-001" }],
    related_capabilities: ["platform_core"],
    tags: ["ui", "shell"],
    last_known_state: "Done",
    synthetic: false,
  },
  {
    id: "doc-11",
    title: "Tasker Board UI",
    slug: "tasker-board-ui",
    category: "ui_contract",
    module: "tasker",
    phase: "approved",
    status: "done",
    summary: "Contrato da UI do Tasker Board.",
    source_path: "docs/ui/surfaces/TASKER_BOARD.md",
    related_docs: [],
    related_tasks: [{ id: "task-2", type: "task", label: "DEV-TASKER-BOARD-001" }],
    related_capabilities: ["platform_core"],
    tags: ["ui", "tasker"],
    last_known_state: "Done",
    synthetic: false,
  },
  {
    id: "doc-12",
    title: "Capability Explorer UI",
    slug: "capability-explorer-ui",
    category: "ui_contract",
    module: "capabilities",
    phase: "approved",
    status: "done",
    summary: "Contrato da UI do Capability Explorer.",
    source_path: "docs/ui/surfaces/CAPABILITY_EXPLORER.md",
    related_docs: [{ id: "doc-16", type: "doc", label: "Capability Registry" }],
    related_tasks: [{ id: "task-3", type: "task", label: "DEV-CAPABILITY-EXPLORER-001" }],
    related_capabilities: ["platform_core"],
    tags: ["ui", "explorer"],
    last_known_state: "Done",
    synthetic: false,
  },
  {
    id: "doc-13",
    title: "Registry View UI",
    slug: "registry-view-ui",
    category: "ui_contract",
    module: "registry",
    phase: "approved",
    status: "done",
    summary: "Contrato da UI do Registry View.",
    source_path: "docs/ui/surfaces/REGISTRY_VIEW.md",
    related_docs: [{ id: "doc-16", type: "doc", label: "Capability Registry" }],
    related_tasks: [{ id: "task-4", type: "task", label: "DEV-REGISTRY-VIEW-001" }],
    related_capabilities: ["platform_core"],
    tags: ["ui", "registry"],
    last_known_state: "Done",
    synthetic: false,
  },
  {
    id: "doc-14",
    title: "Builder Shell Dev Review",
    slug: "builder-shell-review",
    category: "review_report",
    module: "shell",
    phase: "review",
    status: "done",
    summary: "Relatório de revisão técnica da UI do Builder Shell.",
    source_path: "docs/ui/reviews/DEV-REVIEW-BUILDER-SHELL-001_REPORT.md",
    related_docs: [{ id: "doc-10", type: "doc", label: "Builder Shell UI" }],
    related_tasks: [],
    related_capabilities: ["platform_core"],
    tags: ["review"],
    last_known_state: "Approved",
    synthetic: false,
  },
  {
    id: "doc-15",
    title: "Registry View Dev Review",
    slug: "registry-view-review",
    category: "review_report",
    module: "registry",
    phase: "review",
    status: "done",
    summary: "Relatório de revisão técnica da UI do Registry View.",
    source_path: "docs/ui/reviews/DEV-REVIEW-REGISTRY-VIEW-001_REPORT.md",
    related_docs: [{ id: "doc-13", type: "doc", label: "Registry View UI" }],
    related_tasks: [],
    related_capabilities: ["platform_core"],
    tags: ["review"],
    last_known_state: "Approved",
    synthetic: false,
  },
  {
    id: "doc-16",
    title: "Capability Registry",
    slug: "capability-registry",
    category: "registry",
    module: "registry",
    phase: "approved",
    status: "done",
    summary: "Grafo oficial e dependências técnicas das capabilities.",
    source_path: "docs/capabilities/CAPABILITY_REGISTRY.md",
    related_docs: [{ id: "doc-17", type: "doc", label: "Capability Index" }],
    related_tasks: [],
    related_capabilities: ["platform_core"],
    tags: ["capabilities", "registry"],
    last_known_state: "Active",
    synthetic: false,
  },
  {
    id: "doc-17",
    title: "Capability Index",
    slug: "capability-index",
    category: "capability",
    module: "registry",
    phase: "approved",
    status: "done",
    summary: "Índice navegacional de Capabilities Universais no repositório.",
    source_path: "docs/registry/CAPABILITY_INDEX.md",
    related_docs: [{ id: "doc-16", type: "doc", label: "Capability Registry" }],
    related_tasks: [],
    related_capabilities: ["platform_core"],
    tags: ["capabilities", "index"],
    last_known_state: "Active",
    synthetic: false,
  },
  {
    id: "doc-18",
    title: "Docs Viewer Contract",
    slug: "docs-viewer-ui",
    category: "ui_contract",
    module: "docs_viewer",
    phase: "development",
    status: "ready",
    summary: "Contrato principal do próprio visualizador de documentos.",
    source_path: "docs/ui/surfaces/DOCS_VIEWER.md",
    related_docs: [],
    related_tasks: [{ id: "task-5", type: "task", label: "DEV-DOCS-VIEWER-001" }],
    related_capabilities: ["platform_core"],
    tags: ["ui", "docs"],
    last_known_state: "Ready for Dev",
    synthetic: false,
  },
  {
    id: "doc-19",
    title: "Release Readiness Inventory",
    slug: "release-readiness-inventory",
    category: "readiness",
    module: "core",
    phase: "readiness",
    status: "ready",
    summary: "Release Readiness Inventory and Release Checklist.",
    source_path: "docs/operations/RELEASE_READINESS_INVENTORY.md",
    related_docs: [],
    related_tasks: [],
    related_capabilities: ["platform_core"],
    tags: ["readiness", "release", "checklist"],
    last_known_state: "Active",
    synthetic: false,
  }
];