import { Source } from './source-intake-types';

export const mockSources: Source[] = [
  // Technical Service Intake
  {
    id: 'ts-1',
    name: 'Tech Manual A',
    context: 'Technical Service Intake - Synthetic Sources',
    status: 'synthetic',
    evidences: [
      { id: 'e1', title: 'Page 12', type: 'document', description: 'Schema diagram' },
      { id: 'e2', title: 'Page 15', type: 'document', description: 'Wiring instructions' },
      { id: 'e3', title: 'Video A', type: 'video', description: 'Assembly video' },
      { id: 'e4', title: 'Audio Log 1', type: 'audio', description: 'Tech notes' },
      { id: 'e5', title: 'Image Set 1', type: 'image', description: 'Board photos' },
    ],
    limitations: [
      { id: 'l1', description: 'Outdated version' },
      { id: 'l2', description: 'Missing chapter 3' },
    ],
    conflicts: [
      { id: 'c1', description: 'Conflicts with Tech Manual B on voltage' },
    ],
    gaps: [
      { id: 'g1', description: 'No troubleshooting section' },
      { id: 'g2', description: 'Lacks safety warnings' },
    ],
    consentStatus: 'Approved',
    anonymization: 'Fully Anonymized',
    sensitivity: 'Low',
    reliability: 'High',
    retention: '1 Year',
  },
  {
    id: 'ts-2',
    name: 'Tech Manual B',
    context: 'Technical Service Intake - Synthetic Sources',
    status: 'synthetic',
    evidences: [
      { id: 'e1', title: 'E1', type: 'doc', description: 'D1' },
      { id: 'e2', title: 'E2', type: 'doc', description: 'D2' },
      { id: 'e3', title: 'E3', type: 'doc', description: 'D3' },
      { id: 'e4', title: 'E4', type: 'doc', description: 'D4' },
      { id: 'e5', title: 'E5', type: 'doc', description: 'D5' },
    ],
    limitations: [{ id: 'l1', description: 'L1' }, { id: 'l2', description: 'L2' }],
    conflicts: [{ id: 'c1', description: 'C1' }],
    gaps: [{ id: 'g1', description: 'G1' }, { id: 'g2', description: 'G2' }],
    consentStatus: 'Approved',
    anonymization: 'Fully Anonymized',
    sensitivity: 'Low',
    reliability: 'High',
    retention: '1 Year',
  },
  {
    id: 'ts-3',
    name: 'Field Report 1',
    context: 'Technical Service Intake - Synthetic Sources',
    status: 'synthetic',
    evidences: [
      { id: 'e1', title: 'E1', type: 'doc', description: 'D1' },
      { id: 'e2', title: 'E2', type: 'doc', description: 'D2' },
      { id: 'e3', title: 'E3', type: 'doc', description: 'D3' },
      { id: 'e4', title: 'E4', type: 'doc', description: 'D4' },
      { id: 'e5', title: 'E5', type: 'doc', description: 'D5' },
    ],
    limitations: [{ id: 'l1', description: 'L1' }, { id: 'l2', description: 'L2' }],
    conflicts: [{ id: 'c1', description: 'C1' }],
    gaps: [{ id: 'g1', description: 'G1' }, { id: 'g2', description: 'G2' }],
    consentStatus: 'Approved',
    anonymization: 'Fully Anonymized',
    sensitivity: 'Medium',
    reliability: 'Medium',
    retention: '1 Year',
  },
  {
    id: 'ts-4',
    name: 'Operator Log X',
    context: 'Technical Service Intake - Synthetic Sources',
    status: 'real_pending',
    evidences: [
      { id: 'e1', title: 'E1', type: 'doc', description: 'D1' },
      { id: 'e2', title: 'E2', type: 'doc', description: 'D2' },
      { id: 'e3', title: 'E3', type: 'doc', description: 'D3' },
      { id: 'e4', title: 'E4', type: 'doc', description: 'D4' },
      { id: 'e5', title: 'E5', type: 'doc', description: 'D5' },
    ],
    limitations: [{ id: 'l1', description: 'L1' }, { id: 'l2', description: 'L2' }],
    conflicts: [{ id: 'c1', description: 'C1' }],
    gaps: [{ id: 'g1', description: 'G1' }, { id: 'g2', description: 'G2' }],
    consentStatus: 'Pending',
    anonymization: 'Pending',
    sensitivity: 'High',
    reliability: 'Unknown',
    retention: 'TBD',
  },
  {
    id: 'ts-5',
    name: 'Operator Log Y',
    context: 'Technical Service Intake - Synthetic Sources',
    status: 'real_blocked',
    evidences: [
      { id: 'e1', title: 'E1', type: 'doc', description: 'D1' },
      { id: 'e2', title: 'E2', type: 'doc', description: 'D2' },
      { id: 'e3', title: 'E3', type: 'doc', description: 'D3' },
      { id: 'e4', title: 'E4', type: 'doc', description: 'D4' },
      { id: 'e5', title: 'E5', type: 'doc', description: 'D5' },
    ],
    limitations: [{ id: 'l1', description: 'L1' }, { id: 'l2', description: 'L2' }],
    conflicts: [{ id: 'c1', description: 'C1' }],
    gaps: [{ id: 'g1', description: 'G1' }, { id: 'g2', description: 'G2' }],
    consentStatus: 'Denied',
    anonymization: 'N/A',
    sensitivity: 'High',
    reliability: 'Unknown',
    retention: 'N/A',
  },

  // Clinic Appointment Intake
  {
    id: 'ca-1',
    name: 'Schedule Template',
    context: 'Clinic Appointment Intake - Synthetic Sources',
    status: 'synthetic',
    evidences: [
      { id: 'e1', title: 'E1', type: 'doc', description: 'D1' },
      { id: 'e2', title: 'E2', type: 'doc', description: 'D2' },
      { id: 'e3', title: 'E3', type: 'doc', description: 'D3' },
      { id: 'e4', title: 'E4', type: 'doc', description: 'D4' },
      { id: 'e5', title: 'E5', type: 'doc', description: 'D5' },
    ],
    limitations: [{ id: 'l1', description: 'L1' }, { id: 'l2', description: 'L2' }],
    conflicts: [{ id: 'c1', description: 'C1' }],
    gaps: [{ id: 'g1', description: 'G1' }, { id: 'g2', description: 'G2' }],
    consentStatus: 'Approved',
    anonymization: 'Fully Anonymized',
    sensitivity: 'Low',
    reliability: 'High',
    retention: '1 Year',
  },
  {
    id: 'ca-2',
    name: 'Protocol X',
    context: 'Clinic Appointment Intake - Synthetic Sources',
    status: 'synthetic',
    evidences: [
      { id: 'e1', title: 'E1', type: 'doc', description: 'D1' },
      { id: 'e2', title: 'E2', type: 'doc', description: 'D2' },
      { id: 'e3', title: 'E3', type: 'doc', description: 'D3' },
      { id: 'e4', title: 'E4', type: 'doc', description: 'D4' },
      { id: 'e5', title: 'E5', type: 'doc', description: 'D5' },
    ],
    limitations: [{ id: 'l1', description: 'L1' }, { id: 'l2', description: 'L2' }],
    conflicts: [{ id: 'c1', description: 'C1' }],
    gaps: [{ id: 'g1', description: 'G1' }, { id: 'g2', description: 'G2' }],
    consentStatus: 'Approved',
    anonymization: 'Fully Anonymized',
    sensitivity: 'Low',
    reliability: 'High',
    retention: '1 Year',
  },
  {
    id: 'ca-3',
    name: 'Checklist Y',
    context: 'Clinic Appointment Intake - Synthetic Sources',
    status: 'synthetic',
    evidences: [
      { id: 'e1', title: 'E1', type: 'doc', description: 'D1' },
      { id: 'e2', title: 'E2', type: 'doc', description: 'D2' },
      { id: 'e3', title: 'E3', type: 'doc', description: 'D3' },
      { id: 'e4', title: 'E4', type: 'doc', description: 'D4' },
      { id: 'e5', title: 'E5', type: 'doc', description: 'D5' },
    ],
    limitations: [{ id: 'l1', description: 'L1' }, { id: 'l2', description: 'L2' }],
    conflicts: [{ id: 'c1', description: 'C1' }],
    gaps: [{ id: 'g1', description: 'G1' }, { id: 'g2', description: 'G2' }],
    consentStatus: 'Approved',
    anonymization: 'Fully Anonymized',
    sensitivity: 'Low',
    reliability: 'High',
    retention: '1 Year',
  },
  {
    id: 'ca-4',
    name: 'Doctor Notes',
    context: 'Clinic Appointment Intake - Synthetic Sources',
    status: 'real_pending',
    evidences: [
      { id: 'e1', title: 'E1', type: 'doc', description: 'D1' },
      { id: 'e2', title: 'E2', type: 'doc', description: 'D2' },
      { id: 'e3', title: 'E3', type: 'doc', description: 'D3' },
      { id: 'e4', title: 'E4', type: 'doc', description: 'D4' },
      { id: 'e5', title: 'E5', type: 'doc', description: 'D5' },
    ],
    limitations: [{ id: 'l1', description: 'L1' }, { id: 'l2', description: 'L2' }],
    conflicts: [{ id: 'c1', description: 'C1' }],
    gaps: [{ id: 'g1', description: 'G1' }, { id: 'g2', description: 'G2' }],
    consentStatus: 'Pending',
    anonymization: 'Pending',
    sensitivity: 'High',
    reliability: 'Unknown',
    retention: 'TBD',
  },
  {
    id: 'ca-5',
    name: 'Patient Intake Form',
    context: 'Clinic Appointment Intake - Synthetic Sources',
    status: 'real_blocked',
    evidences: [
      { id: 'e1', title: 'E1', type: 'doc', description: 'D1' },
      { id: 'e2', title: 'E2', type: 'doc', description: 'D2' },
      { id: 'e3', title: 'E3', type: 'doc', description: 'D3' },
      { id: 'e4', title: 'E4', type: 'doc', description: 'D4' },
      { id: 'e5', title: 'E5', type: 'doc', description: 'D5' },
    ],
    limitations: [{ id: 'l1', description: 'L1' }, { id: 'l2', description: 'L2' }],
    conflicts: [{ id: 'c1', description: 'C1' }],
    gaps: [{ id: 'g1', description: 'G1' }, { id: 'g2', description: 'G2' }],
    consentStatus: 'Denied',
    anonymization: 'N/A',
    sensitivity: 'High',
    reliability: 'Unknown',
    retention: 'N/A',
  },

  // Workshop Repair Intake
  {
    id: 'wr-1',
    name: 'Diagnostic Tool Manual',
    context: 'Workshop Repair Intake - Synthetic Sources',
    status: 'synthetic',
    evidences: [
      { id: 'e1', title: 'E1', type: 'doc', description: 'D1' },
      { id: 'e2', title: 'E2', type: 'doc', description: 'D2' },
      { id: 'e3', title: 'E3', type: 'doc', description: 'D3' },
      { id: 'e4', title: 'E4', type: 'doc', description: 'D4' },
      { id: 'e5', title: 'E5', type: 'doc', description: 'D5' },
    ],
    limitations: [{ id: 'l1', description: 'L1' }, { id: 'l2', description: 'L2' }],
    conflicts: [{ id: 'c1', description: 'C1' }],
    gaps: [{ id: 'g1', description: 'G1' }, { id: 'g2', description: 'G2' }],
    consentStatus: 'Approved',
    anonymization: 'Fully Anonymized',
    sensitivity: 'Low',
    reliability: 'High',
    retention: '1 Year',
  },
  {
    id: 'wr-2',
    name: 'Safety Guidelines',
    context: 'Workshop Repair Intake - Synthetic Sources',
    status: 'synthetic',
    evidences: [
      { id: 'e1', title: 'E1', type: 'doc', description: 'D1' },
      { id: 'e2', title: 'E2', type: 'doc', description: 'D2' },
      { id: 'e3', title: 'E3', type: 'doc', description: 'D3' },
      { id: 'e4', title: 'E4', type: 'doc', description: 'D4' },
      { id: 'e5', title: 'E5', type: 'doc', description: 'D5' },
    ],
    limitations: [{ id: 'l1', description: 'L1' }, { id: 'l2', description: 'L2' }],
    conflicts: [{ id: 'c1', description: 'C1' }],
    gaps: [{ id: 'g1', description: 'G1' }, { id: 'g2', description: 'G2' }],
    consentStatus: 'Approved',
    anonymization: 'Fully Anonymized',
    sensitivity: 'Low',
    reliability: 'High',
    retention: '1 Year',
  },
  {
    id: 'wr-3',
    name: 'Standard Operating Procedure 1',
    context: 'Workshop Repair Intake - Synthetic Sources',
    status: 'synthetic',
    evidences: [
      { id: 'e1', title: 'E1', type: 'doc', description: 'D1' },
      { id: 'e2', title: 'E2', type: 'doc', description: 'D2' },
      { id: 'e3', title: 'E3', type: 'doc', description: 'D3' },
      { id: 'e4', title: 'E4', type: 'doc', description: 'D4' },
      { id: 'e5', title: 'E5', type: 'doc', description: 'D5' },
    ],
    limitations: [{ id: 'l1', description: 'L1' }, { id: 'l2', description: 'L2' }],
    conflicts: [{ id: 'c1', description: 'C1' }],
    gaps: [{ id: 'g1', description: 'G1' }, { id: 'g2', description: 'G2' }],
    consentStatus: 'Approved',
    anonymization: 'Fully Anonymized',
    sensitivity: 'Low',
    reliability: 'High',
    retention: '1 Year',
  },
  {
    id: 'wr-4',
    name: 'Mechanic Logbook',
    context: 'Workshop Repair Intake - Synthetic Sources',
    status: 'real_pending',
    evidences: [
      { id: 'e1', title: 'E1', type: 'doc', description: 'D1' },
      { id: 'e2', title: 'E2', type: 'doc', description: 'D2' },
      { id: 'e3', title: 'E3', type: 'doc', description: 'D3' },
      { id: 'e4', title: 'E4', type: 'doc', description: 'D4' },
      { id: 'e5', title: 'E5', type: 'doc', description: 'D5' },
    ],
    limitations: [{ id: 'l1', description: 'L1' }, { id: 'l2', description: 'L2' }],
    conflicts: [{ id: 'c1', description: 'C1' }],
    gaps: [{ id: 'g1', description: 'G1' }, { id: 'g2', description: 'G2' }],
    consentStatus: 'Pending',
    anonymization: 'Pending',
    sensitivity: 'High',
    reliability: 'Unknown',
    retention: 'TBD',
  },
  {
    id: 'wr-5',
    name: 'Customer Request Form',
    context: 'Workshop Repair Intake - Synthetic Sources',
    status: 'real_blocked',
    evidences: [
      { id: 'e1', title: 'E1', type: 'doc', description: 'D1' },
      { id: 'e2', title: 'E2', type: 'doc', description: 'D2' },
      { id: 'e3', title: 'E3', type: 'doc', description: 'D3' },
      { id: 'e4', title: 'E4', type: 'doc', description: 'D4' },
      { id: 'e5', title: 'E5', type: 'doc', description: 'D5' },
    ],
    limitations: [{ id: 'l1', description: 'L1' }, { id: 'l2', description: 'L2' }],
    conflicts: [{ id: 'c1', description: 'C1' }],
    gaps: [{ id: 'g1', description: 'G1' }, { id: 'g2', description: 'G2' }],
    consentStatus: 'Denied',
    anonymization: 'N/A',
    sensitivity: 'High',
    reliability: 'Unknown',
    retention: 'N/A',
  },
];
